<?php
/* =========================================================================
   HTCCC – Baptismal Applications (PHPMailer + individual_table email)
   - Accept = schedule + email (clean message)
   - Email now uses individual_table.individual_email_address
   - ENUM case fallback (Scheduled -> scheduled)
   - Sync individual_table.baptism_verification
   - Test endpoint: ?ajax=test_mail&to=someone@example.com

   NOTE: In notifications table, created_by_id now stores the FULL NAME
         of the admin (e.g. "Paglicawan, Ashley") instead of the numeric ID.
         Make sure notifications.created_by_id is a VARCHAR (or similar).

   NEW:
   - PDF now shows "Generated by: <logged-in admin full name>"
     (pulled from admin table: admin_lastname/admin_firstname/admin_middlename)
   ======================================================================== */

include 'db-connection.php';
if (!isset($db_connection) || !$db_connection instanceof mysqli) {
  http_response_code(500);
  echo "Database connection missing.";
  exit;
}
mysqli_set_charset($db_connection, 'utf8mb4');
mysqli_query($db_connection, "SET collation_connection = 'utf8mb4_general_ci'");

/* Ensure session available for admin identity */
if (session_status() !== PHP_SESSION_ACTIVE) {
  @session_start();
}

/* =========================
   Admin display name (DB)
   - Pulls from admin table using session admin_id
   ========================= */
function htccc_admin_display_name_from_db(mysqli $db_connection): string {
  if (session_status() !== PHP_SESSION_ACTIVE) {
    @session_start();
  }

  // CHANGE THIS if your admin table name is different
  $adminTable = 'admin_table';

  // Admin id from session (adjust if your system uses different key)
  $adminId = 0;
  if (!empty($_SESSION['admin_id'])) {
    $adminId = (int)$_SESSION['admin_id'];
  } elseif (!empty($_SESSION['user_id'])) {
    $adminId = (int)$_SESSION['user_id'];
  }

  // If cannot resolve ID, fallback to any session name if exists
  if ($adminId <= 0) {
    if (!empty($_SESSION['admin_lastname']) || !empty($_SESSION['admin_firstname'])) {
      $ln = trim((string)($_SESSION['admin_lastname'] ?? ''));
      $fn = trim((string)($_SESSION['admin_firstname'] ?? ''));
      $mn = trim((string)($_SESSION['admin_middlename'] ?? ''));
      $out = trim($ln . ', ' . $fn . ' ' . $mn);
      return trim(preg_replace('/\s+/', ' ', $out)) ?: 'Admin';
    }
    return 'Admin';
  }

  // Title-case helper
  $titleCase = function ($s) {
    $s = trim((string)$s);
    if ($s === '') return '';
    return preg_replace_callback(
      '/\b(\p{L})(\p{L}*)/u',
      fn($m) => mb_strtoupper($m[1]).mb_strtolower($m[2]),
      $s
    );
  };

  // Query admin table
  $sql = "SELECT admin_lastname, admin_firstname, admin_middlename
          FROM {$adminTable}
          WHERE admin_id = ?
          LIMIT 1";

  if ($stmt = mysqli_prepare($db_connection, $sql)) {
    mysqli_stmt_bind_param($stmt, "i", $adminId);
    mysqli_stmt_execute($stmt);
    $res = mysqli_stmt_get_result($stmt);

    if ($row = mysqli_fetch_assoc($res)) {
      $ln = $titleCase($row['admin_lastname'] ?? '');
      $fn = $titleCase($row['admin_firstname'] ?? '');
      $mn = $titleCase($row['admin_middlename'] ?? '');

      mysqli_stmt_close($stmt);

      $name = '';

      // Format: Lastname, Firstname Middlename
      if ($ln !== '' && $fn !== '') {
        $name = $ln . ', ' . $fn;
      } elseif ($ln !== '') {
        $name = $ln;
      } elseif ($fn !== '') {
        $name = $fn;
      }

      if ($mn !== '') {
        $name .= ($name !== '' ? ' ' : '') . $mn;
      }

      return $name !== '' ? $name : ('Admin #' . $adminId);
    }

    mysqli_stmt_close($stmt);
  }

  return 'Admin #' . $adminId;
}

/* =========================
   PHPMailer (manual includes)
   ========================= */
require_once __DIR__ . '/PHPMailer/src/Exception.php';
require_once __DIR__ . '/PHPMailer/src/PHPMailer.php';
require_once __DIR__ . '/PHPMailer/src/SMTP.php';

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;

/* =========================
   Mail helper
   ========================= */
function htccc_send_mail($toEmail, $toName, $subject, $bodyPlain) {
  if (!filter_var($toEmail, FILTER_VALIDATE_EMAIL)) {
    return ['ok'=>false, 'error'=>'Invalid recipient email', 'error_info'=>''];
  }

  $mail = new PHPMailer(true);
  try {
    $mail->isSMTP();
    $mail->Host       = 'smtp.gmail.com';
    $mail->SMTPAuth   = true;
    $mail->Username   = 'holytrinitychristiancommunityc@gmail.com'; // Gmail address

    // SAFETY: keep your real app password here (you already have it)
    $mail->Password   = 'PUT_YOUR_APP_PASSWORD_HERE';

    $mail->SMTPSecure = PHPMailer::ENCRYPTION_STARTTLS;
    $mail->Port       = 587;
    $mail->CharSet    = 'UTF-8';

    $mail->setFrom('holytrinitychristiancommunityc@gmail.com', 'HTCCC');
    $mail->addAddress($toEmail, $toName ?: $toEmail);

    $mail->isHTML(false);
    $mail->Subject = (string)$subject;
    $mail->Body    = (string)$bodyPlain;
    $mail->AltBody = (string)$bodyPlain;

    $mail->send();
    return ['ok'=>true, 'error'=>'', 'error_info'=>''];
  } catch (Exception $e) {
    return ['ok'=>false, 'error'=>'Mailer Error', 'error_info'=>$mail->ErrorInfo];
  }
}

function h($v){ return htmlspecialchars($v ?? '', ENT_QUOTES, 'UTF-8'); }

/**
 * Turn a DB path into a public URL the browser can load.
 */
function htccc_public_url_from_path($path) {
  $path = trim((string)$path);
  if ($path === '') return '';

  $path = str_replace('\\', '/', $path);

  if (preg_match('#^https?://#i', $path)) {
    return $path;
  }

  $scheme  = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https://' : 'http://';
  $host    = isset($_SERVER['HTTP_HOST']) ? $_SERVER['HTTP_HOST'] : 'localhost';
  $baseUrl = rtrim($scheme . $host, '/');

  $scriptDir    = rtrim(dirname($_SERVER['PHP_SELF']), '/\\'); // "/HTCCC-SYSTEM"
  $rootDirName  = trim($scriptDir, '/');                       // "HTCCC-SYSTEM"

  if (strlen($path) && $path[0] === '/') {
    return $baseUrl . $path;
  }

  if ($rootDirName !== '' && stripos($path, $rootDirName . '/') === 0) {
    return $baseUrl . '/' . ltrim($path, '/');
  }

  return $baseUrl . $scriptDir . '/' . ltrim($path, '/');
}

/* =====================================================================
   Admin → Individual notification helper (mysqli version)
   ===================================================================== */
if (!function_exists('notifyIndividualFromAdmin_mysqli')) {
  function notifyIndividualFromAdmin_mysqli(
    mysqli $db_connection,
    int $individualId,
    string $actionKey,
    string $serviceLabel,
    ?int $recordId = null,
    ?string $assignedDateYmd = null
  ): bool {

    if ($individualId <= 0) return false;

    if (session_status() !== PHP_SESSION_ACTIVE) {
      @session_start();
    }

    $createdByType = 'admin';

    $createdById = isset($_SESSION['user_id']) ? (int)$_SESSION['user_id'] : 0;
    if ($createdById <= 0 && isset($_SESSION['admin_id'])) {
      $createdById = (int)$_SESSION['admin_id'];
    }
    if ($createdById <= 0) return false;

    // Pull admin display from DB
    $adminDisplay = htccc_admin_display_name_from_db($db_connection);

    $actionKey = strtolower(trim($actionKey));
    $serviceLabel = trim($serviceLabel) !== '' ? trim($serviceLabel) : 'Service';
    $actionLabel = 'Updated';

    if (
      $actionKey === 'accept' ||
      $actionKey === 'approved' ||
      str_contains($actionKey, 'accept') ||
      str_contains($actionKey, 'approve')
    ) {
      $actionLabel = 'Approved';
    } elseif ($actionKey === 'reupload' || str_contains($actionKey, 'reupload')) {
      $actionLabel = 'Reupload Required';
    } elseif (
      $actionKey === 'reject' ||
      $actionKey === 'rejected' ||
      $actionKey === 'cancel' ||
      $actionKey === 'cancelled' ||
      str_contains($actionKey, 'reject') ||
      str_contains($actionKey, 'cancel')
    ) {
      $actionLabel = 'Rejected';
    }

    if ($assignedDateYmd !== null) {
      $assignedDateYmd = substr(trim($assignedDateYmd), 0, 10);
    }
    if (!$assignedDateYmd || !preg_match('/^\d{4}-\d{2}-\d{2}$/', $assignedDateYmd)) {
      $assignedDateYmd = date('Y-m-d');
    }

    $title = $serviceLabel . ' – ' . $actionLabel;
    $recordIdPart = ($recordId !== null && $recordId > 0) ? (string)$recordId : '-';

    $lines = [];
    $lines[] = 'Admin: ' . $adminDisplay;
    $lines[] = 'Action: ' . $actionLabel;
    $lines[] = 'Service: ' . $serviceLabel;
    $lines[] = 'Record ID: ' . $recordIdPart;
    $lines[] = 'Summary: ' . $serviceLabel . ' | Status: ' . $actionLabel . ' • Date: ' . $assignedDateYmd;

    $body = implode("\n", $lines);

    if (function_exists('mb_strlen')) {
      if (mb_strlen($body) > 2000) $body = mb_substr($body, 0, 2000);
    } else {
      if (strlen($body) > 2000) $body = substr($body, 0, 2000);
    }

    $titleEsc         = mysqli_real_escape_string($db_connection, $title);
    $bodyEsc          = mysqli_real_escape_string($db_connection, $body);
    $createdByTypeEsc = mysqli_real_escape_string($db_connection, $createdByType);

    // created_by_id stores FULL NAME string
    $createdByNameEsc = mysqli_real_escape_string($db_connection, $adminDisplay);

    $sqlNotif = "
      INSERT INTO notifications (title, body, created_by_type, created_by_id)
      VALUES ('{$titleEsc}', '{$bodyEsc}', '{$createdByTypeEsc}', '{$createdByNameEsc}')
    ";

    if (!mysqli_query($db_connection, $sqlNotif)) return false;

    $notificationId = (int)mysqli_insert_id($db_connection);
    if ($notificationId <= 0) return false;

    $sqlRec = "
      INSERT INTO notification_recipients (notification_id, user_type, user_id, status)
      VALUES ({$notificationId}, 'individual', {$individualId}, 'unread')
    ";

    if (!mysqli_query($db_connection, $sqlRec)) return false;

    return true;
  }
}

/* =========================
   AJAX
   ========================= */
if (isset($_GET['ajax'])) {
  header('Content-Type: application/json; charset=utf-8');

  // SMTP sanity test
  if ($_GET['ajax'] === 'test_mail') {
    $to = trim($_GET['to'] ?? '');
    $res = htccc_send_mail($to, $to, 'HTCCC SMTP Test', "Hello,\nThis is a test email from HTCCC.\nTime: ".date('c'));
    echo json_encode($res + ['to'=>$to]);
    exit;
  }

  // 1) Detail
  if ($_GET['ajax'] === 'detail') {
    $id = isset($_GET['id']) ? (int)$_GET['id'] : 0;
    $ok = false; $data = [];
    if ($id > 0) {
      $sql = "SELECT baptism_id,baptized_lastname,baptized_firstname,baptized_middlename,baptized_ext,
                     created_at,service_status,baptismal_cert_path,
                     guardian_lastname,guardian_firstname,guardian_middlename,guardian_ext,guardian_contactnum,
                     email_address,individual_id,service_date
              FROM service_baptism WHERE baptism_id=? LIMIT 1";
      if ($stmt = mysqli_prepare($db_connection, $sql)) {
        mysqli_stmt_bind_param($stmt, "i", $id);
        mysqli_stmt_execute($stmt);
        $res = mysqli_stmt_get_result($stmt);
        if ($row = mysqli_fetch_assoc($res)) {
          $certPath = isset($row['baptismal_cert_path']) ? $row['baptismal_cert_path'] : '';
          $row['baptismal_cert_full_url'] = htccc_public_url_from_path($certPath);
          $ok = true;
          $data = $row;
        }
        mysqli_stmt_close($stmt);
      }
    }
    echo json_encode(['ok'=>$ok, 'data'=>$data]); exit;
  }

  // 2) Occupied dates
  if ($_GET['ajax'] === 'occupied') {
    $dates = [];
    $sql = "SELECT DISTINCT DATE(service_date) AS d
            FROM service_baptism
            WHERE service_date IS NOT NULL AND service_date <> '0000-00-00'";
    if ($res = mysqli_query($db_connection, $sql)) {
      while ($r = mysqli_fetch_assoc($res)) if (!empty($r['d'])) $dates[] = $r['d'];
      mysqli_free_result($res);
    }
    echo json_encode(['ok'=>true, 'occupied'=>$dates]); exit;
  }

  // 3) Update status
  if ($_GET['ajax'] === 'update_status') {
    $payload = [];
    if (stripos($_SERVER['CONTENT_TYPE'] ?? '', 'application/json') !== false) {
      $payload = json_decode(file_get_contents('php://input'), true) ?: [];
    } else {
      $payload = $_POST;
      if (isset($payload['ids']) && is_string($payload['ids'])) {
        $decoded = json_decode($payload['ids'], true);
        if (is_array($decoded)) $payload['ids'] = $decoded;
      }
    }

    $action = strtolower(trim($payload['action'] ?? ''));
    $ids    = $payload['ids'] ?? [];
    $msg    = trim((string)($payload['message'] ?? ''));
    $service_date = isset($payload['service_date']) ? trim((string)$payload['service_date']) : null;

    if (!in_array($action, ['accept','reupload','reject'], true)) { echo json_encode(['ok'=>false,'error'=>'Invalid action']); exit; }
    if (!is_array($ids) || !count($ids)) { echo json_encode(['ok'=>false,'error'=>'No IDs selected']); exit; }
    foreach ($ids as $i){ if (!is_numeric($i)) { echo json_encode(['ok'=>false,'error'=>'Invalid ID in list']); exit; } }
    $ids = array_map('intval', $ids);
    $in  = implode(',', $ids);

    $status_accept_primary  = 'Scheduled';
    $status_accept_fallback = 'scheduled';
    $status_reupload        = 'Reupload';
    $status_reject          = 'Cancelled';

    if ($action==='accept') {
      if (!$service_date || !preg_match('/^\d{4}-\d{2}-\d{2}$/', $service_date)) { echo json_encode(['ok'=>false,'error'=>'Missing or invalid service_date']); exit; }
      if (strtotime($service_date) < strtotime(date('Y-m-d'))) { echo json_encode(['ok'=>false,'error'=>'service_date cannot be in the past']); exit; }
    }

    mysqli_begin_transaction($db_connection);
    try {
      $affected_svc = 0;
      if ($action==='accept') {
        $sd_esc = mysqli_real_escape_string($db_connection, $service_date);
        $st_esc = mysqli_real_escape_string($db_connection, $status_accept_primary);
        $sqlU = "UPDATE service_baptism SET service_status='{$st_esc}', service_date='{$sd_esc}' WHERE baptism_id IN ({$in})";
        if (!mysqli_query($db_connection, $sqlU)) throw new Exception('Update failed: '.mysqli_error($db_connection));
        $affected_svc = mysqli_affected_rows($db_connection);

        if ($affected_svc === 0) {
          $st_esc = mysqli_real_escape_string($db_connection, $status_accept_fallback);
          $sqlU2 = "UPDATE service_baptism SET service_status='{$st_esc}', service_date='{$sd_esc}' WHERE baptism_id IN ({$in})";
          if (!mysqli_query($db_connection, $sqlU2)) throw new Exception('Update (fallback) failed: '.mysqli_error($db_connection));
          $affected_svc = mysqli_affected_rows($db_connection);
        }
      } else {
        $new_status = ($action==='reupload') ? $status_reupload : $status_reject;
        $st_esc = mysqli_real_escape_string($db_connection, $new_status);
        $sqlU = "UPDATE service_baptism SET service_status='{$st_esc}' WHERE baptism_id IN ({$in})";
        if (!mysqli_query($db_connection, $sqlU)) throw new Exception('Update failed: '.mysqli_error($db_connection));
        $affected_svc = mysqli_affected_rows($db_connection);
      }

      $verification = null;
      if     ($action==='accept')   $verification = 'Pending';
      elseif ($action==='reupload') $verification = 'Reupload';
      elseif ($action==='reject')   $verification = 'NonVerified';

      $affected_ind = 0;
      if ($verification !== null) {
        $ver_esc = mysqli_real_escape_string($db_connection, $verification);
        $sqlV = "UPDATE individual_table i
                 JOIN service_baptism s ON s.individual_id = i.individual_id
                 SET i.baptism_verification = '{$ver_esc}'
                 WHERE s.baptism_id IN ({$in})";
        if (!mysqli_query($db_connection, $sqlV)) throw new Exception('Verification update failed: '.mysqli_error($db_connection));
        $affected_ind = mysqli_affected_rows($db_connection);
      }

      $sqlS = "SELECT 
                  s.baptism_id,
                  s.individual_id,
                  i.individual_email_address AS email_address,
                  s.baptized_firstname,
                  s.baptized_lastname,
                  COALESCE(s.service_date, s.created_at) AS svc_date
               FROM service_baptism s
               LEFT JOIN individual_table i ON i.individual_id = s.individual_id
               WHERE s.baptism_id IN ({$in})";
      $res = mysqli_query($db_connection, $sqlS);
      if (!$res) throw new Exception('Select failed: '.mysqli_error($db_connection));
      $rows = [];
      while($r = mysqli_fetch_assoc($res)) $rows[] = $r;
      mysqli_free_result($res);

      if (!empty($rows) && function_exists('notifyIndividualFromAdmin_mysqli')) {
        foreach ($rows as $r) {
          $indId     = isset($r['individual_id']) ? (int)$r['individual_id'] : 0;
          $baptismId = isset($r['baptism_id'])    ? (int)$r['baptism_id']    : null;
          if ($indId <= 0) continue;

          $notifActionKey = 'baptism_' . $action;
          $serviceLabel = 'Baptism Application';

          $assignedRaw = null;
          if (!empty($r['svc_date'])) $assignedRaw = substr((string)$r['svc_date'], 0, 10);
          if (!$assignedRaw || !preg_match('/^\d{4}-\d{2}-\d{2}$/', $assignedRaw)) $assignedRaw = date('Y-m-d');

          try {
            notifyIndividualFromAdmin_mysqli(
              $db_connection,
              $indId,
              $notifActionKey,
              $serviceLabel,
              $baptismId,
              $assignedRaw
            );
          } catch (Throwable $____e) {}
        }
      }

      $sent=0; $fail=0; $errList=[];
      foreach ($rows as $r) {
        $to  = trim((string)($r['email_address'] ?? ''));
        $fn  = trim(($r['baptized_firstname'] ?? '').' '.($r['baptized_lastname'] ?? ''));

        if ($action === 'accept') {
          $svc  = $service_date ?: substr((string)$r['svc_date'], 0, 10);
          $human = $svc ? date('F j, Y', strtotime($svc)) : null;
          $subject = "HTCCC Baptism Schedule";
          $line = $human
            ? "Your baptism has been scheduled for {$human}. Please arrive on that date."
            : "Your baptism has been scheduled. Please arrive on the scheduled date.";
          $body = "Dear {$fn},\n\n{$line}\n";
          if ($msg !== '') { $body .= "\nNote from the admin:\n{$msg}\n"; }
          $body .= "\nThank you,\nHTCCC";
        } elseif ($action === 'reupload') {
          $subject = "HTCCC Baptism: Reupload Required";
          $body = "Dear {$fn},\n\nYour baptism application requires a reupload of your documents.\n";
          if ($msg !== '') { $body .= "\nNote from the admin:\n{$msg}\n"; }
          $body .= "\nThank you,\nHTCCC";
        } else {
          $subject = "HTCCC Baptism Application Update";
          $body = "Dear {$fn},\n\nWe’re sorry to inform you that your application was cancelled.\n";
          if ($msg !== '') { $body .= "\nNote from the admin:\n{$msg}\n"; }
          $body .= "\nThank you,\nHTCCC";
        }

        if ($to !== '') {
          $sendRes = htccc_send_mail($to, $fn, $subject, $body);
          if ($sendRes['ok']) $sent++;
          else { $fail++; $errList[] = ['to'=>$to, 'error'=>$sendRes['error_info'] ?: $sendRes['error']]; }
        }
      }

      mysqli_commit($db_connection);
      echo json_encode([
        'ok'=>true,
        'updated'=>($affected_svc + $affected_ind),
        'row_updates'=>['service_baptism'=>$affected_svc,'individual_table'=>$affected_ind],
        'emails_sent'=>$sent,
        'emails_failed'=>$fail,
        'email_errors'=>$errList
      ]);
      exit;

    } catch (Exception $e) {
      mysqli_rollback($db_connection);
      error_log('[BAPTISM update_status] '.$e->getMessage());
      echo json_encode(['ok'=>false,'error'=>'Server error: '.$e->getMessage()]); exit;
    }
  }

  echo json_encode(['ok'=>false,'error'=>'Unknown ajax action']); exit;
}

/* =======================================================================
   BAPTISMAL PDF GENERATORS (LIST + DETAIL)
   ======================================================================= */

if (isset($_GET['download']) && $_GET['download'] === 'baptism_list_pdf') {
  try {
    $statusKey = strtolower(trim($_GET['status'] ?? 'all'));
    $statusMap = [
      'pending'   => 'Pending',
      'scheduled' => 'Scheduled',
      'reupload'  => 'Reupload',
      'all'       => 'all'
    ];
    $filterStatus = $statusMap[$statusKey] ?? 'all';

    $sqlPdf = "
      SELECT sb.baptism_id,
             sb.baptized_lastname,
             sb.baptized_firstname,
             sb.baptized_middlename,
             sb.baptized_ext,
             sb.created_at,
             sb.service_status,
             sb.individual_id
      FROM service_baptism sb
      JOIN (
          SELECT individual_id, MAX(created_at) AS max_created
          FROM service_baptism
          WHERE service_status IN ('Pending','Scheduled','Reupload')
          GROUP BY individual_id
      ) latest
        ON latest.individual_id = sb.individual_id
       AND latest.max_created   = sb.created_at
      WHERE sb.service_status IN ('Pending','Scheduled','Reupload')
    ";

    if ($filterStatus !== 'all') {
      $sqlPdf .= " AND sb.service_status = '" . mysqli_real_escape_string($db_connection, $filterStatus) . "'";
    }

    $sqlPdf .= "
      ORDER BY FIELD(sb.service_status,'Pending','Scheduled','Reupload'),
               sb.created_at DESC
    ";

    $res = mysqli_query($db_connection, $sqlPdf);
    if (!$res) throw new Exception('Query failed: ' . mysqli_error($db_connection));

    $rows = [];
    while ($r = mysqli_fetch_assoc($res)) { $rows[] = $r; }
    mysqli_free_result(($res ?? null));

    $host  = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS']==='on' ? 'https://' : 'http://') . $_SERVER['HTTP_HOST'];
    $logo  = $host . '/HTCCC-SYSTEM/image/httc_main-logo.jpg';
    $titleSuffix = ($filterStatus === 'all') ? 'All Statuses' : $filterStatus;
    $title = 'Baptismal Applications – ' . $titleSuffix;
    $nowStr = date('F j, Y g:i A');

    // NEW: generated by
    $generatedBy = htccc_admin_display_name_from_db($db_connection);

    $html = '<!doctype html><html><head><meta charset="utf-8"><style>
      *{box-sizing:border-box}
      body{font-family:DejaVu Sans,Arial,Helvetica,sans-serif;color:#0b1220;margin:0;padding:24px}
      .header{display:flex;align-items:center;gap:14px;margin-bottom:6px}
      .logo{width:52px;height:52px;object-fit:cover;border-radius:8px}
      h1{font-size:18px;margin:0}
      .meta{font-size:12px;color:#4b5563}
      .bar{height:4px;background:#00216e;border-radius:4px;margin:10px 0 16px}
      table{width:100%;border-collapse:collapse;font-size:12px}
      thead th{background:#00216e;color:#fff;text-align:left;padding:10px;font-weight:700}
      tbody td{padding:8px 10px;border-bottom:1px solid #e6edf5;vertical-align:top}
      .small{color:#374151;font-size:11px}
      .badge{display:inline-block;padding:2px 8px;border-radius:999px;font-size:11px}
      .badge.Pending{background:#fff7e6}
      .badge.Scheduled{background:#e0f2fe}
      .badge.Reupload{background:#eef2ff}
      </style></head><body>';

    $html .= '<div class="header">
                <img class="logo" src="'.htmlspecialchars($logo,ENT_QUOTES,'UTF-8').'" alt="HTCCC">
                <div>
                  <h1>'.htmlspecialchars($title,ENT_QUOTES,'UTF-8').'</h1>
                  <div class="meta">
                    Generated: '.htmlspecialchars($nowStr,ENT_QUOTES,'UTF-8').'<br>
                    Generated by: '.htmlspecialchars($generatedBy,ENT_QUOTES,'UTF-8').'
                  </div>
                </div>
              </div>
              <div class="bar"></div>';

    $html .= '<table><thead><tr>
                <th style="width:16%">Last Name</th>
                <th style="width:16%">First Name</th>
                <th style="width:16%">Middle Name</th>
                <th style="width:8%">Ext</th>
                <th style="width:18%">Date Applied</th>
                <th style="width:12%">Status</th>
                <th style="width:14%">Individual ID</th>
              </tr></thead><tbody>';

    if (!empty($rows)) {
      foreach ($rows as $r) {
        $ln = htmlspecialchars($r['baptized_lastname'] ?? '', ENT_QUOTES, 'UTF-8');
        $fn = htmlspecialchars($r['baptized_firstname'] ?? '', ENT_QUOTES, 'UTF-8');
        $mn = htmlspecialchars($r['baptized_middlename'] ?? '', ENT_QUOTES, 'UTF-8');
        $ex = htmlspecialchars($r['baptized_ext'] ?? '', ENT_QUOTES, 'UTF-8');
        $st = (string)($r['service_status'] ?? '');
        $stEsc = htmlspecialchars($st, ENT_QUOTES, 'UTF-8');
        $badgeClass = 'badge ' . preg_replace('/[^A-Za-z]/','',$st);
        $created = $r['created_at'] ?? '';
        $prettyDate = $created ? date('F j, Y', strtotime($created)) : '';
        $prettyDate = htmlspecialchars($prettyDate,ENT_QUOTES,'UTF-8');
        $indId = htmlspecialchars((string)($r['individual_id'] ?? ''), ENT_QUOTES, 'UTF-8');

        $html .= '<tr>
          <td>'.$ln.'</td>
          <td>'.$fn.'</td>
          <td>'.$mn.'</td>
          <td>'.$ex.'</td>
          <td>'.$prettyDate.'</td>
          <td><span class="'.$badgeClass.'">'.$stEsc.'</span></td>
          <td>'.$indId.'</td>
        </tr>';
      }
    } else {
      $html .= '<tr><td colspan="7" class="small">No records found for this filter.</td></tr>';
    }

    $html .= '</tbody></table></body></html>';

    require_once __DIR__ . '/vendor/autoload.php';
    $options = new Dompdf\Options();
    $options->set('isRemoteEnabled', true);
    $options->set('defaultFont', 'DejaVu Sans');

    $dompdf = new Dompdf\Dompdf($options);
    $dompdf->loadHtml($html, 'UTF-8');
    $dompdf->setPaper('A4', 'portrait');
    $dompdf->render();

    $fileStatus = ($filterStatus === 'all') ? 'All' : $filterStatus;
    $filename = 'Baptismal_Applications_'.$fileStatus.'_'.date('Y-m-d_His').'.pdf';
    $dompdf->stream($filename, ['Attachment' => true]);
    exit;

  } catch (Throwable $e) {
    if (!headers_sent()) header('Content-Type: text/plain; charset=utf-8');
    echo "Failed to generate PDF.\n\n".$e->getMessage();
    exit;
  }
}

if (isset($_GET['download']) && $_GET['download'] === 'baptism_detail_pdf') {
  $id = isset($_GET['id']) ? (int)$_GET['id'] : 0;
  if ($id <= 0) {
    if (!headers_sent()) header('Content-Type: text/plain; charset=utf-8');
    echo "Invalid ID."; exit;
  }

  try {
    $sql = "SELECT baptism_id,baptized_lastname,baptized_firstname,baptized_middlename,baptized_ext,
                   created_at,service_status,baptismal_cert_path,
                   guardian_lastname,guardian_firstname,guardian_middlename,guardian_ext,guardian_contactnum,
                   email_address,individual_id,service_date
            FROM service_baptism
            WHERE baptism_id=? LIMIT 1";
    $row = null;
    if ($stmt = mysqli_prepare($db_connection, $sql)) {
      mysqli_stmt_bind_param($stmt, "i", $id);
      mysqli_stmt_execute($stmt);
      $res = mysqli_stmt_get_result($stmt);
      if ($res && $tmp = mysqli_fetch_assoc($res)) $row = $tmp;
      mysqli_stmt_close($stmt);
    }

    if (!$row) {
      if (!headers_sent()) header('Content-Type: text/plain; charset=utf-8');
      echo "Record not found."; exit;
    }

    $ln = $row['baptized_lastname'] ?? '';
    $fn = $row['baptized_firstname'] ?? '';
    $mn = $row['baptized_middlename'] ?? '';
    $ex = $row['baptized_ext'] ?? '';

    $fullNameParts = array_filter([$fn, $mn, $ln, $ex], fn($v) => trim((string)$v) !== '');
    $fullName = implode(' ', $fullNameParts);
    if ($fullName === '') $fullName = 'N/A';

    $createdPretty = $row['created_at'] ? date('F j, Y g:i A', strtotime($row['created_at'])) : 'N/A';
    $servicePretty = $row['service_date'] ? date('F j, Y', strtotime($row['service_date'])) : 'Not yet scheduled';

    $statusLabel = (string)($row['service_status'] ?? '');
    $statusLabelEsc = htmlspecialchars($statusLabel, ENT_QUOTES, 'UTF-8');

    $gLn = $row['guardian_lastname'] ?? '';
    $gFn = $row['guardian_firstname'] ?? '';
    $gMn = $row['guardian_middlename'] ?? '';
    $gEx = $row['guardian_ext'] ?? '';
    $gCn = $row['guardian_contactnum'] ?? '';

    $guardianNameParts = array_filter([$gFn, $gMn, $gLn, $gEx], fn($v) => trim((string)$v) !== '');
    $guardianFull = implode(' ', $guardianNameParts);
    if ($guardianFull === '') $guardianFull = 'N/A';

    $email = $row['email_address'] ?? '';
    $indId = $row['individual_id'] ?? '';

    $certPath = trim((string)($row['baptismal_cert_path'] ?? ''));
    $certStatus = $certPath !== '' ? 'Provided' : 'Not Provided';

    $host  = (isset($_SERVER['HTTPS']) && $_SERVER['HTTPS']==='on' ? 'https://' : 'http://') . $_SERVER['HTTP_HOST'];
    $logo  = $host . '/HTCCC-SYSTEM/image/httc_main-logo.jpg';
    $title = 'Baptismal Application Details';
    $nowStr = date('F j, Y g:i A');

    // NEW: generated by
    $generatedBy = htccc_admin_display_name_from_db($db_connection);

    $html = '<!doctype html><html><head><meta charset="utf-8"><style>
      *{box-sizing:border-box}
      body{font-family:DejaVu Sans,Arial,Helvetica,sans-serif;color:#0b1220;margin:0;padding:24px}
      .header{display:flex;align-items:center;gap:14px;margin-bottom:6px}
      .logo{width:52px;height:52px;object-fit:cover;border-radius:8px}
      h1{font-size:18px;margin:0}
      .meta{font-size:12px;color:#4b5563}
      .bar{height:4px;background:#00216e;border-radius:4px;margin:10px 0 16px}
      .section-title{font-weight:700;font-size:13px;margin:12px 0 6px;color:#111827}
      table{width:100%;border-collapse:collapse;font-size:12px;margin-bottom:8px}
      td{padding:6px 8px;border-bottom:1px solid #e5e7eb;vertical-align:top}
      td.label{width:28%;font-weight:700;color:#374151;background:#f9fafb}
      .small{font-size:11px;color:#6b7280}
      </style></head><body>';

    $html .= '<div class="header">
                <img class="logo" src="'.htmlspecialchars($logo,ENT_QUOTES,'UTF-8').'" alt="HTCCC">
                <div>
                  <h1>'.htmlspecialchars($title,ENT_QUOTES,'UTF-8').'</h1>
                  <div class="meta">
                    Generated: '.htmlspecialchars($nowStr,ENT_QUOTES,'UTF-8').'<br>
                    Generated by: '.htmlspecialchars($generatedBy,ENT_QUOTES,'UTF-8').'
                  </div>
                </div>
              </div>
              <div class="bar"></div>';

    $html .= '<div class="section">
                <div class="section-title">Applicant</div>
                <table>
                  <tr><td class="label">Full Name</td><td>'.htmlspecialchars($fullName,ENT_QUOTES,'UTF-8').'</td></tr>
                  <tr><td class="label">Last Name</td><td>'.htmlspecialchars($ln,ENT_QUOTES,'UTF-8').'</td></tr>
                  <tr><td class="label">First Name</td><td>'.htmlspecialchars($fn,ENT_QUOTES,'UTF-8').'</td></tr>
                  <tr><td class="label">Middle Name</td><td>'.htmlspecialchars($mn,ENT_QUOTES,'UTF-8').'</td></tr>
                  <tr><td class="label">Extension</td><td>'.htmlspecialchars($ex,ENT_QUOTES,'UTF-8').'</td></tr>
                  <tr><td class="label">Individual ID</td><td>'.htmlspecialchars((string)$indId,ENT_QUOTES,'UTF-8').'</td></tr>
                  <tr><td class="label">Email</td><td>'.htmlspecialchars($email,ENT_QUOTES,'UTF-8').'</td></tr>
                </table>
              </div>';

    $html .= '<div class="section">
                <div class="section-title">Baptismal Status</div>
                <table>
                  <tr><td class="label">Status</td><td>'.$statusLabelEsc.'</td></tr>
                  <tr><td class="label">Date Applied</td><td>'.htmlspecialchars($createdPretty,ENT_QUOTES,'UTF-8').'</td></tr>
                  <tr><td class="label">Service Date</td><td>'.htmlspecialchars($servicePretty,ENT_QUOTES,'UTF-8').'</td></tr>
                  <tr><td class="label">Baptismal Certificate Image</td><td>'.htmlspecialchars($certStatus,ENT_QUOTES,'UTF-8').'</td></tr>
                </table>
              </div>';

    $html .= '<div class="section">
                <div class="section-title">Guardian</div>
                <table>
                  <tr><td class="label">Guardian Name</td><td>'.htmlspecialchars($guardianFull,ENT_QUOTES,'UTF-8').'</td></tr>
                  <tr><td class="label">Guardian Last Name</td><td>'.htmlspecialchars($gLn,ENT_QUOTES,'UTF-8').'</td></tr>
                  <tr><td class="label">Guardian First Name</td><td>'.htmlspecialchars($gFn,ENT_QUOTES,'UTF-8').'</td></tr>
                  <tr><td class="label">Guardian Middle Name</td><td>'.htmlspecialchars($gMn,ENT_QUOTES,'UTF-8').'</td></tr>
                  <tr><td class="label">Guardian Extension</td><td>'.htmlspecialchars($gEx,ENT_QUOTES,'UTF-8').'</td></tr>
                  <tr><td class="label">Guardian Contact Number</td><td>'.htmlspecialchars($gCn,ENT_QUOTES,'UTF-8').'</td></tr>
                </table>
              </div>';

    $html .= '<p class="small">Note: The field &ldquo;Baptismal Certificate Image&rdquo; only indicates whether a certificate image was provided in the application (Provided / Not Provided).</p>';
    $html .= '</body></html>';

    require_once __DIR__ . '/vendor/autoload.php';
    $options = new Dompdf\Options();
    $options->set('isRemoteEnabled', true);
    $options->set('defaultFont', 'DejaVu Sans');

    $dompdf = new Dompdf\Dompdf($options);
    $dompdf->loadHtml($html, 'UTF-8');
    $dompdf->setPaper('A4', 'portrait');
    $dompdf->render();

    $fileNameSafe = preg_replace('/[^A-Za-z0-9_\-]+/', '_', $fullName);
    if ($fileNameSafe === '') $fileNameSafe = 'Baptismal_Application';
    $filename = $fileNameSafe.'_ID'.$id.'_'.date('Y-m-d_His').'.pdf';
    $dompdf->stream($filename, ['Attachment' => true]);
    exit;

  } catch (Throwable $e) {
    if (!headers_sent()) header('Content-Type: text/plain; charset=utf-8');
    echo "Failed to generate detail PDF.\n\n".$e->getMessage();
    exit;
  }
}

/* =========================
   MAIN TABLE
   ========================= */

$sql = "
  SELECT sb.baptism_id,
         sb.baptized_lastname,
         sb.baptized_firstname,
         sb.baptized_middlename,
         sb.baptized_ext,
         sb.created_at,
         sb.service_status,
         sb.individual_id
  FROM service_baptism sb
  JOIN (
      SELECT individual_id, MAX(created_at) AS max_created
      FROM service_baptism
      WHERE service_status IN ('Pending','Scheduled','Reupload')
      GROUP BY individual_id
  ) latest
    ON latest.individual_id = sb.individual_id
   AND latest.max_created   = sb.created_at
  WHERE sb.service_status IN ('Pending','Scheduled','Reupload')
  ORDER BY FIELD(sb.service_status,'Pending','Scheduled','Reupload'),
           sb.created_at DESC
";

$result = mysqli_query($db_connection, $sql);
?>
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta content="width=device-width, initial-scale=1"/>
  <title>HTCCC – Baptismal Applications</title>

  <link rel="icon" type="image/x-icon" href="image/httc_main-logo.jpg">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">

  <!-- SweetAlert2 CDN -->
  <script src="https://cdn.jsdelivr.net/npm/sweetalert2@11"></script>

  <style>
    :root{--card-bg:#fff;--navy-ink:#0a0d2b;--ink:#0f172a;--row-sep:#eef2f7;--radius-xl:18px}
    *{box-sizing:border-box}
    body{margin:0;background:#f6f7fb;color:var(--ink);font-family:system-ui,-apple-system,Segoe UI,Roboto,Arial}
    .page{padding:22px}
    .card{position:relative;background:var(--card-bg);border:1px solid #e5e7eb;border-radius:var(--radius-xl);box-shadow:0 8px 24px rgba(20,23,38,.06);overflow:hidden}
    .section-title-wrap{padding:14px 18px 12px}
    .section-title{font-size:22px;font-weight:800;color:#0b1533;margin:0 0 8px}
    .table-wrap{overflow:auto}
    table{width:100%;border-collapse:separate;border-spacing:0;font-size:15px}
    thead th{background:var(--navy-ink);color:#fff;font-weight:700;text-align:left;padding:14px 16px;border-bottom:1px solid rgba(255,255,255,.08);white-space:nowrap}
    thead th:first-child{border-top-left-radius:14px}
    thead th:last-child{border-top-right-radius:14px}
    tbody td{padding:14px 16px;border-bottom:1px solid var(--row-sep);vertical-align:middle}
    tbody tr:hover{background:#fbfcff}
    .td--date{white-space:nowrap}
    .badge{display:inline-block;background:#e8f7ee;color:#127c3e;border:1px solid #bde9ce;border-radius:999px;padding:6px 12px;font-size:13px;font-weight:700}
    .badge.pending{background:#fff7e6;color:#8a5b00;border-color:#ffe0a3}
    .badge.reupload{background:#eef2ff;color:#1e3a8a;border-color:#c7d2fe}
    .badge.cancelled{background:#ffecec;color:#a3001a;border-color:#ffc4cc}
    .badge.scheduled{background:#e0f2fe;color:#075985;border-color:#bfdbfe}
    .btn{display:inline-flex;align-items:center;gap:8px;background:#1a1a64;color:#fff;border:1px solid #0b0e2a;border-radius:999px;padding:8px 14px;cursor:pointer}
    .btn-secondary{padding:8px 12px;border:1px solid #e5e7eb;border-radius:10px;background:#f5f7fb;color:#111;cursor:pointer}
    .btn-secondary.disabled{opacity:.55;cursor:not-allowed}
    .action-bar{position:absolute;right:16px;top:12px;display:flex;gap:8px;align-items:center;flex-wrap:wrap;justify-content:flex-end}
    .chip{border:1px solid #e5e7eb;background:#f8fafc;border-radius:999px;padding:8px 12px;font-size:13px;cursor:pointer;display:inline-flex;align-items:center;gap:6px}
    .chip.primary{background:#111827;color:#fff;border-color:#0b0e2a}
    .count{font-weight:700}
    #statusSortSelect{font-size:13px;background:transparent;border:none;outline:none;padding:2px 4px}

    /* Modal */
    .backdrop{position:fixed;inset:0;background:rgba(17,24,39,.55);display:none;align-items:center;justify-content:center;z-index:1000}
    .backdrop.open{display:flex}
    .modal{width:min(820px,94vw);background:#fff;border-radius:16px;border:1px solid #e5e7eb;box-shadow:0 20px 60px rgba(0,0,0,.35);overflow:hidden}
    .modal.modal-image{width:min(980px,96vw);}
    .modal-head{display:grid;grid-template-columns:1fr auto;align-items:center;gap:12px;padding:14px 16px;background:linear-gradient(180deg,#f8fafc,#f1f5f9);border-bottom:1px solid #e5e7eb}
    .modal-head h3{margin:0;font-size:18px}
    .close-btn{background:#0f172a;color:#fff;border:none;border-radius:10px;padding:8px 12px;cursor:pointer}
    .modal-body{padding:16px}
    .grid{display:grid;grid-template-columns:repeat(2, minmax(0,1fr));gap:12px}
    .grid label{display:block;font-size:12px;color:#64748b;margin-bottom:4px}
    .hidden{display:none}

    /* Floating Calendar */
    .sd-backdrop{position:fixed;inset:0;background:rgba(15,23,42,.4);display:none;align-items:center;justify-content:center;z-index:1100}
    .sd-backdrop.open{display:flex}
    .sd-panel{background:#fff;border-radius:16px;border:1px solid #e5e7eb;box-shadow:0 20px 60px rgba(0,0,0,.35);width:min(480px,94vw);padding:14px}
    .sd-head{display:flex;justify-content:space-between;align-items:center;margin-bottom:8px}
    .sd-grid{display:grid;grid-template-columns:repeat(7,1fr);gap:6px}
    .sd-cell{padding:10px 0;text-align:center;border:1px solid #e5e7eb;border-radius:10px;cursor:pointer}
    .sd-cell.header{background:#f8fafc;font-weight:700;cursor:default}
    .sd-cell.occupied{background:#fff2f2;border-color:#fecaca}
    .sd-cell.past{opacity:.45;pointer-events:none}
    .sd-cell.selected{outline:2px solid #111827}
    .sd-pill{display:inline-block;font-size:11px;margin-top:4px;padding:2px 6px;border-radius:999px;background:#e5e7eb}

    /* Sidebar */
    :root{--nav:#00216e}
    .sidebar{position:fixed;inset:0 auto 0 0;width:280px;background:var(--nav);color:#fff;display:flex;flex-direction:column;padding:18px 16px;overflow-y:auto;z-index:900}
    .brand{display:flex;align-items:center;gap:10px;font-weight:800}
    .brand img{width:26px;height:26px;border-radius:6px}
    .brand span{letter-spacing:.2px}
    .user-card{display:flex;align-items:center;gap:12px;padding:12px 8px;background:rgba(255,255,255,.05);border-radius:12px;margin:14px 0}
    .user-card img{width:40px;height:40px;border-radius:999px}
    .user-title{font-weight:700}
    .user-sub{font-size:12px;color:#cbd5e1}
    .nav{display:flex;flex-direction:column;gap:6px}
    .section-title{margin-top:12px;margin-bottom:6px;font-size:11px;letter-spacing:.08em;color:#93a4b8;text-transform:uppercase}
    .navlink{display:flex;align-items:center;gap:10px;color:#e2e8f0;text-decoration:none;padding:10px 12px;border-radius:10px}
    .navlink:hover{background:rgba(255,255,255,.06)}
    .navlink.active{background:#1f2937;color:#fff}
    .navlink.logout{color:#fca5a5}
    .page{margin-left:280px}
    @media (max-width:920px){.sidebar{width:240px}.page{margin-left:240px}}
    @media (max-width:720px){.sidebar{position:static;width:auto}.page{margin:0}}
  </style>
</head>
<body>

  <aside class="sidebar">
    <div class="brand">
      <img src="image/httc_main-logo.jpg" alt="" />
      <span>HTCCC SYSTEM</span>
    </div>
    <div class="user-card">
      <img src="css/image/profile.png" alt="user">
      <div>
        <div class="user-title">Secretary</div>
        <div class="user-sub">Dashboard</div>
      </div>
    </div>
    <nav class="nav">
      <div class="section-title">Main</div>
      <a class="navlink" href="secretary_dashboard.php"><i class="fas fa-home"></i>Dashboard</a>
      <div class="section-title">Online Requests</div>
      <a class="navlink" href="admin-schedule-request.php"><i class="fas fa-calendar-plus"></i>Schedule Requests</a>
      <a class="navlink" href="admin-prayer-request.php"><i class="fas fa-praying-hands"></i><span>Prayer Requests</span></a>
      <div class="section-title">Online Applications</div>
      <a class="navlink active" href="baptismal_application.php"><i class="fas fa-water"></i>Baptismal Applications</a>
      <a class="navlink" href="admin-application.php"><i class="fas fa-user-cog"></i>Baptismal Account Verification</a>
      <a class="navlink" href="application_ministry.php"><i class="fas fa-users"></i>Ministry Applications</a>
      <div class="section-title">Schedule</div>
      <a class="navlink" href="appointment-schedule.php"><i class="fas fa-calendar-check"></i>Service Schedule</a>
      <div class="section-title">All Done Services</div>
      <a class="navlink" href="done-service-wedding.php"><i class="fas fa-ring"></i>Wedding Service</a>
      <a class="navlink" href="done-service-dedication.php"><i class="fas fa-baby"></i>Child Dedication</a>
      <a class="navlink" href="done-service-funeral.php"><i class="fas fa-cross"></i>Funeral Service</a>
      <a class="navlink" href="done-service-house.php"><i class="fas fa-home"></i>House Blessing</a>
      <a class="navlink" href="done-service-baptism.php"><i class="fas fa-tint"></i>Water Baptism</a>
      <div class="section-title">Streaming</div>
      <a class="navlink" href="admin-multimedia.php"><i class="fas fa-broadcast-tower"></i>Streaming</a>
       <div class="section-title">Individual Management</div>
      <a class="navlink" href="admin-individual_list.php"><i class="fas fa-user"></i>Individual List</a>
      <div class="section-title">Ministry Management</div>
      <a class="navlink" href="admin-ministry-women.php"><i class="fas fa-female"></i>Handmaid of the Lord</a>
      <a class="navlink" href="admin-ministry-men.php"><i class="fas fa-male"></i>Men Ministry</a>
      <a class="navlink" href="admin-ministry-music.php"><i class="fas fa-music"></i>Music Ministry</a>
      <a class="navlink" href="admin-ministry-usher.php"><i class="fas fa-hands-helping"></i>Usher &amp; Usherette</a>
      <div class="section-title">Reports</div>
      <a class="navlink" href="admin-reports.php"><i class="fas fa-file-alt"></i>Reports</a>
      <div class="section-title">Content</div>
      <a class="navlink" href="content-management_home-page.php"><i class="fas fa-edit"></i>Content Management</a>
      <div class="section-title">Certificates</div>
      <a class="navlink" href="certificate-table.php"><i class="fas fa-award"></i>Generate Certificate</a>
      <div class="section-title">Account</div>
      <a class="navlink" href="admin-account-settings.php"><i class="fas fa-user-shield"></i>Account Settings</a>
      <div class="section-title">More</div>
      <a class="navlink logout" href="all_log-in.php"><i class="fas fa-sign-out-alt"></i>Log Out</a>
    </nav>
  </aside>

  <div class="page">
    <div class="card">
      <div class="section-title-wrap">
        <h2 class="section-title">Baptismal Applications</h2>
      </div>

      <div class="action-bar" aria-label="Bulk Actions">
        <span class="chip" id="btnSelectAll"><i class="fas fa-check-square"></i> Select all</span>
        <span class="chip" id="btnReupload"><i class="fas fa-sync"></i> Reupload</span>
        <span class="chip" id="btnReject"><i class="fas fa-times-circle"></i> Reject</span>
        <span class="chip primary" id="btnAccept"><i class="fas fa-calendar-check"></i> Accept</span>
        <span class="chip">Selected: <span class="count" id="selCount">0</span></span>

        <span class="chip" id="statusSortWrap">
          <i class="fas fa-filter"></i>
          <span>Status:</span>
          <select id="statusSortSelect">
            <option value="">All statuses</option>
            <option value="pending">Pending only</option>
            <option value="scheduled">Scheduled only</option>
            <option value="reupload">Reupload only</option>
          </select>
        </span>
      </div>

      <div class="table-wrap">
        <table role="table" aria-label="Baptism applications" id="bapTable">
          <thead>
            <tr>
              <th style="width:70px">Select</th>
              <th>Last Name</th>
              <th>First Name</th>
              <th>Middle Name</th>
              <th>Extension</th>
              <th class="td--date">Date Applied</th>
              <th>Status</th>
              <th style="text-align:center;width:120px">Action</th>
            </tr>
          </thead>
          <tbody>
            <?php
            if ($result && mysqli_num_rows($result) > 0) {
              $rowIndex = 0;
              while ($row = mysqli_fetch_assoc($result)) {
                $rawDate = $row['created_at'] ?? '';
                $pretty  = $rawDate ? date('F j, Y', strtotime($rawDate)) : '—';
                $status  = strtolower(trim((string)$row['service_status']));
                $badgeClass = 'badge';
                if ($status === 'pending')   $badgeClass .= ' pending';
                if ($status === 'reupload')  $badgeClass .= ' reupload';
                if ($status === 'cancelled') $badgeClass .= ' cancelled';
                if ($status === 'scheduled') $badgeClass .= ' scheduled';

                $id  = (int)$row['baptism_id'];
                $ind = isset($row['individual_id']) ? (int)$row['individual_id'] : 0;

                echo "<tr data-orig-index='{$rowIndex}' data-status='{$status}' data-individual-id='{$ind}'>";
                  echo "<td style='text-align:center'><input type='checkbox' class='rowcb' data-id='{$id}' aria-label='Select row'></td>";
                  echo "<td>".h($row['baptized_lastname'])."</td>";
                  echo "<td>".h($row['baptized_firstname'])."</td>";
                  echo "<td>".h($row['baptized_middlename'])."</td>";
                  echo "<td>".h($row['baptized_ext'])."</td>";
                  echo "<td class='td--date'>".h($pretty)."</td>";
                  echo "<td><span class='{$badgeClass}'>".h($row['service_status'])."</span></td>";
                  echo "<td style='text-align:center'><button class='btn btn-view' data-id='{$id}' type='button'><i class='fas fa-eye'></i> View</button></td>";
                echo "</tr>";
                $rowIndex++;
              }
            } else {
              echo '<tr><td colspan="8" style="padding:18px;color:#475569">No records found.</td></tr>';
            }
            ?>
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <!-- Detail Modal -->
  <div class="backdrop" id="detailBackdrop" role="dialog" aria-modal="true" aria-hidden="true">
    <div class="modal">
      <div class="modal-head">
        <h3>Application Details</h3>
        <button class="close-btn" id="detailClose"><i class="fas fa-times"></i> Close</button>
      </div>
      <div class="modal-body">
        <div class="grid">
          <div><label>Lastname</label><div id="d_ln">—</div></div>
          <div><label>Firstname</label><div id="d_fn">—</div></div>
          <div><label>Middlename</label><div id="d_mn">—</div></div>
          <div><label>Extension</label><div id="d_ex">—</div></div>
          <div><label>Date Applied</label><div id="d_created">—</div></div>
          <div><label>Service Date</label><div id="d_svcdate">—</div></div>
        </div>

        <div style="margin-top:12px;display:flex;align-items:center;gap:8px">
          <button id="btnShowCert" class="btn-secondary" type="button">
            <i class="far fa-image"></i> View Certificate Image
          </button>
          <span id="certHint" style="font-size:12px;color:#9ca3af;"></span>
        </div>

        <div id="guardianBlock" class="hidden" style="margin-top:16px">
          <h4 style="margin:0 0 8px">Guardian</h4>
          <div class="grid">
            <div><label>Guardian Lastname</label><div id="g_ln">—</div></div>
            <div><label>Guardian Firstname</label><div id="g_fn">—</div></div>
            <div><label>Guardian Middlename</label><div id="g_mn">—</div></div>
            <div><label>Guardian Extension</label><div id="g_ex">—</div></div>
            <div><label>Guardian Contact Number</label><div id="g_cn">—</div></div>
          </div>
        </div>

        <div style="margin-top:18px;display:flex;justify-content:flex-end">
          <button id="detailPdfBtn" class="btn" type="button">
            <i class="fas fa-file-pdf"></i> Download PDF
          </button>
        </div>
      </div>
    </div>
  </div>

  <!-- Certificate Image Modal -->
  <div class="backdrop" id="certBackdrop" role="dialog" aria-modal="true" aria-hidden="true">
    <div class="modal modal-image">
      <div class="modal-head">
        <h3>Certificate Image</h3>
        <button class="close-btn" id="certClose"><i class="fas fa-times"></i> Close</button>
      </div>
      <div class="modal-body" style="text-align:center">
        <img
          id="certModalImg"
          alt="Baptismal Certificate"
          style="max-width:100%;max-height:70vh;border-radius:12px;box-shadow:0 18px 45px rgba(15,23,42,.45)"
        >
      </div>
    </div>
  </div>

  <!-- Accept Modal -->
  <div class="backdrop" id="acceptBackdrop" role="dialog" aria-modal="true" aria-hidden="true">
    <div class="modal">
      <div class="modal-head">
        <h3>Accept & Schedule</h3>
        <button class="close-btn" id="acceptClose"><i class="fas fa-times"></i> Close</button>
      </div>
      <div class="modal-body">
        <div class="grid">
          <div>
            <label>Service Date</label>
            <div style="display:flex;gap:8px;align-items:center">
              <input id="service_date" type="text" readonly style="flex:1;border:1px solid #e5e7eb;border-radius:10px;padding:10px" placeholder="YYYY-MM-DD"/>
              <button id="pickDate" type="button" class="btn-secondary">Pick</button>
            </div>
          </div>
          <div>
            <label>Message to Applicant (included in email)</label>
            <textarea id="acceptMessage" rows="4" style="width:100%;border:1px solid #e5e7eb;border-radius:10px;padding:10px" placeholder="Optional note…"></textarea>
          </div>
        </div>
        <div style="margin-top:12px;display:flex;justify-content:flex-end;gap:8px">
          <button id="acceptSubmit" class="btn" type="button"><i class="fas fa-check"></i> Confirm Accept</button>
        </div>
      </div>
    </div>
  </div>

  <!-- Floating Calendar -->
  <div class="sd-backdrop" id="sdBackdrop" role="dialog" aria-modal="true" aria-hidden="true">
    <div class="sd-panel">
      <div class="sd-head">
        <button id="sdPrev" class="btn-secondary" type="button">&laquo; Prev</button>
        <div id="sdLabel" style="font-weight:800"></div>
        <button id="sdNext" class="btn-secondary" type="button">Next &raquo;</button>
      </div>
      <div id="sdGrid" class="sd-grid"></div>
      <div style="margin-top:10px;display:flex;justify-content:flex-end;gap:8px">
        <button id="sdCancel" class="btn-secondary" type="button">Cancel</button>
        <button id="sdApply" class="btn" type="button"><i class="far fa-calendar-check"></i> Apply</button>
      </div>
    </div>
  </div>

<script>
const $  = (s,ctx=document)=>ctx.querySelector(s);
const $$ = (s,ctx=document)=>Array.from(ctx.querySelectorAll(s));

const selCount = $('#selCount');
function getSelectedIds(){ return $$('#bapTable tbody .rowcb:checked').map(cb => parseInt(cb.dataset.id||'0',10)).filter(Boolean); }
$('#btnSelectAll')?.addEventListener('click', ()=>{ const boxes=$$('#bapTable tbody .rowcb'); const all=boxes.length&&boxes.every(b=>b.checked); boxes.forEach(b=>b.checked=!all); selCount.textContent=getSelectedIds().length; });
$('#bapTable')?.addEventListener('change', e=>{ if(e.target.matches('.rowcb')) selCount.textContent=getSelectedIds().length; });

let currentDetail=null;
let currentDetailId=null;
let currentCertUrl='';

async function fetchDetail(id){
  const res=await fetch(`<?php echo basename(__FILE__); ?>?ajax=detail&id=${encodeURIComponent(id)}`,{headers:{'X-Requested-With':'XMLHttpRequest'}});
  return res.json();
}

document.addEventListener('click', async (e)=>{
  const btn=e.target.closest('.btn-view'); if(!btn) return;
  const id=+btn.dataset.id;
  const json=await fetchDetail(id);
  if(!json.ok){ alert('Details not found'); return; }
  const r=json.data||{}; currentDetail=r; currentDetailId = r.baptism_id || id;

  $('#d_ln').textContent=r.baptized_lastname||'—';
  $('#d_fn').textContent=r.baptized_firstname||'—';
  $('#d_mn').textContent=r.baptized_middlename||'—';
  $('#d_ex').textContent=r.baptized_ext||'—';
  $('#d_created').textContent=r.created_at||'—';
  $('#d_svcdate').textContent=r.service_date||'—';

  const hasG=['guardian_lastname','guardian_firstname','guardian_middlename','guardian_ext','guardian_contactnum']
    .some(k=>(r[k]??'').toString().trim()!=='');
  const gblk=$('#guardianBlock');
  if(hasG){
    gblk.classList.remove('hidden');
    $('#g_ln').textContent=r.guardian_lastname||'—';
    $('#g_fn').textContent=r.guardian_firstname||'—';
    $('#g_mn').textContent=r.guardian_middlename||'—';
    $('#g_ex').textContent=r.guardian_ext||'—';
    $('#g_cn').textContent=r.guardian_contactnum||'—';
  } else {
    gblk.classList.add('hidden');
  }

  currentCertUrl = ((r.baptismal_cert_full_url || r.baptismal_cert_path || '') + '').trim();
  const certBtn  = $('#btnShowCert');
  const certHint = $('#certHint');

  if (!currentCertUrl) {
    certBtn.classList.add('disabled');
    certBtn.disabled = true;
    if (certHint) certHint.textContent = 'No certificate image uploaded.';
  } else {
    certBtn.classList.remove('disabled');
    certBtn.disabled = false;
    if (certHint) certHint.textContent = '';
  }

  const bd=$('#detailBackdrop');
  bd.classList.add('open');
  bd.setAttribute('aria-hidden','false');
});

const certBackdrop = $('#certBackdrop');
const certModalImg = $('#certModalImg');

$('#btnShowCert')?.addEventListener('click', ()=>{
  if(!currentCertUrl){
    alert('No certificate image provided.');
    return;
  }
  certModalImg.src = currentCertUrl;
  certBackdrop.classList.add('open');
  certBackdrop.setAttribute('aria-hidden','false');
});

$('#certClose')?.addEventListener('click', ()=>{
  certBackdrop.classList.remove('open');
  certBackdrop.setAttribute('aria-hidden','true');
  certModalImg.src = '';
});

certBackdrop?.addEventListener('click', e=>{
  if(e.target.id==='certBackdrop'){
    certBackdrop.classList.remove('open');
    certBackdrop.setAttribute('aria-hidden','true');
    certModalImg.src = '';
  }
});

$('#detailClose')?.addEventListener('click', ()=>{
  $('#detailBackdrop').classList.remove('open');
  $('#detailBackdrop').setAttribute('aria-hidden','true');
});

$('#detailBackdrop')?.addEventListener('click', e=>{
  if(e.target.id==='detailBackdrop') {
    e.currentTarget.classList.remove('open');
    e.currentTarget.setAttribute('aria-hidden','true');
  }
});

document.addEventListener('keydown', e=>{
  if(e.key==='Escape'){
    $('#detailBackdrop')?.classList.remove('open');
    $('#detailBackdrop')?.setAttribute('aria-hidden','true');
    $('#certBackdrop')?.classList.remove('open');
    $('#certBackdrop')?.setAttribute('aria-hidden','true');
    if (certModalImg) certModalImg.src = '';
  }
});

$('#detailPdfBtn')?.addEventListener('click', ()=>{
  if(!currentDetailId){
    alert('No application is loaded yet.');
    return;
  }
  const href = "<?php echo basename(__FILE__); ?>?download=baptism_detail_pdf&id=" + encodeURIComponent(currentDetailId);
  window.open(href, "_blank");
});

const ab=$('#acceptBackdrop');
function openAccept(){ ab.classList.add('open'); ab.setAttribute('aria-hidden','false'); }
function closeAccept(){ ab.classList.remove('open'); ab.setAttribute('aria-hidden','true'); }

$('#btnAccept')?.addEventListener('click', ()=>{
  const ids=getSelectedIds();
  if(!ids.length){ alert('Select at least one row.'); return; }
  openAccept();
});
$('#acceptClose')?.addEventListener('click', closeAccept);
$('#acceptBackdrop')?.addEventListener('click', e=>{ if(e.target.id==='acceptBackdrop') closeAccept(); });

const sdb=$('#sdBackdrop'), sdGrid=$('#sdGrid'), sdLabel=$('#sdLabel'), serviceDateInput=$('#service_date');
let cur=new Date(); cur.setDate(1); let pendingPick=null; let OCCUPIED=new Set();

async function loadOccupied(){
  try{
    const res=await fetch(`<?php echo basename(__FILE__); ?>?ajax=occupied`,{headers:{'X-Requested-With':'XMLHttpRequest'}});
    const j=await res.json();
    if(j.ok&&Array.isArray(j.occupied)) OCCUPIED=new Set(j.occupied);
  }catch(e){OCCUPIED=new Set();}
}

function fmtYmd(d){ return d.toISOString().slice(0,10); }
function isPast(date){
  const today=new Date(); today.setHours(0,0,0,0);
  const dd=new Date(date.getFullYear(),date.getMonth(),date.getDate());
  return dd.getTime()<today.getTime();
}
function renderCal(){
  sdGrid.innerHTML='';
  const y=cur.getFullYear(), m=cur.getMonth();
  sdLabel.textContent=cur.toLocaleString(undefined,{month:'long',year:'numeric'});
  ['Sun','Mon','Tue','Wed','Thu','Fri','Sat'].forEach(w=>{
    const c=document.createElement('div');
    c.className='sd-cell header'; c.textContent=w;
    sdGrid.appendChild(c);
  });
  const firstDow=new Date(y,m,1).getDay(), daysInM=new Date(y,m+1,0).getDate();
  for(let i=0;i<firstDow;i++){
    const c=document.createElement('div');
    c.className='sd-cell header'; c.textContent='';
    sdGrid.appendChild(c);
  }
  for(let d=1; d<=daysInM; d++){
    const date=new Date(y,m,d);
    const c=document.createElement('div');
    c.className='sd-cell';
    c.textContent=d;
    const ymd=fmtYmd(date);
    if(isPast(date)) c.classList.add('past');
    if(OCCUPIED.has(ymd)){
      c.classList.add('occupied');
      const pill=document.createElement('div');
      pill.className='sd-pill';
      pill.textContent='FULL';
      c.appendChild(pill);
    }
    if(pendingPick && fmtYmd(pendingPick)===ymd) c.classList.add('selected');
    c.addEventListener('click',()=>{
      if(c.classList.contains('past')) return;
      pendingPick=date; renderCal();
    });
    sdGrid.appendChild(c);
  }
}

$('#pickDate')?.addEventListener('click', async ()=>{
  await loadOccupied();
  sdb.classList.add('open');
  sdb.setAttribute('aria-hidden','false');
  pendingPick=null;
  cur=new Date(); cur.setDate(1);
  renderCal();
});
$('#sdPrev')?.addEventListener('click', ()=>{ cur.setMonth(cur.getMonth()-1); renderCal(); });
$('#sdNext')?.addEventListener('click', ()=>{ cur.setMonth(cur.getMonth()+1); renderCal(); });
$('#sdCancel')?.addEventListener('click', ()=>{
  sdb.classList.remove('open');
  sdb.setAttribute('aria-hidden','true');
});
$('#sdApply')?.addEventListener('click', ()=>{
  if(!pendingPick){ alert('Please pick a date'); return; }
  serviceDateInput.value=fmtYmd(pendingPick);
  sdb.classList.remove('open');
  sdb.setAttribute('aria-hidden','true');
});

async function postUpdate(action, extra){
  const ids=getSelectedIds();
  if(!ids.length){ alert('Select at least one row.'); return; }
  const payload=Object.assign({action,ids}, extra||{});
  const res=await fetch(`<?php echo basename(__FILE__); ?>?ajax=update_status`, {
    method:'POST',
    headers:{'Content-Type':'application/json','X-Requested-With':'XMLHttpRequest'},
    body: JSON.stringify(payload)
  });
  let json={};
  try{ json=await res.json(); }catch(e){ alert('Error: Invalid server response'); return; }
  if(!json.ok){ alert('Error: ' + (json.error || 'Unknown')); return; }
  let msg=`Updated ${json.updated||0} row(s).\nEmails sent: ${json.emails_sent||0}`;
  if((json.emails_failed||0)>0){
    msg += `\nEmails failed: ${json.emails_failed}\n(See browser console -> response JSON for error_info.)`;
    console.warn(json.email_errors);
  }
  alert(msg);
  location.reload();
}
window.postUpdate = postUpdate;
window.getSelectedIds = getSelectedIds;

$('#acceptSubmit')?.addEventListener('click', ()=>{
  const svc=(document.querySelector('#service_date').value||'').trim();
  if(!svc){ alert('Service date is required'); return; }
  const message=($('#acceptMessage').value||'').trim();
  postUpdate('accept',{service_date:svc,message});
});
$('#btnReupload')?.addEventListener('click', async ()=>{
  const ids=getSelectedIds();
  if(!ids.length){ alert('Select at least one row.'); return; }
  const msg=prompt('Reupload\n(Optional) Enter a message to include in the email:');
  if(msg===null) return;
  postUpdate('reupload',{message:(msg||'').trim()});
});
$('#btnReject')?.addEventListener('click', async ()=>{
  const ids=getSelectedIds();
  if(!ids.length){ alert('Select at least one row.'); return; }
  const msg=prompt('Reject\n(Optional) Enter a message to include in the email:');
  if(msg===null) return;
  postUpdate('reject',{message:(msg||'').trim()});
});
</script>

<script>
  window.htcccAlert = function (opts) {
    if (typeof Swal === "undefined") {
      alert(opts && opts.text ? opts.text : "Notice");
      return;
    }
    const {
      title = "Notice",
      text  = "",
      icon  = "info",
      confirmButtonText = "OK"
    } = (opts || {});
    Swal.fire({
      icon: icon,
      title: title,
      text: text,
      confirmButtonText: confirmButtonText
    });
  };

  window.htcccAlertSuccess = function (text) {
    window.htcccAlert({ title: "Success", text: text || "", icon: "success" });
  };
  window.htcccAlertError = function (text) {
    window.htcccAlert({ title: "Error", text: text || "", icon: "error" });
  };
  window.htcccAlertWarning = function (text) {
    window.htcccAlert({ title: "Warning", text: text || "", icon: "warning" });
  };
  window.htcccAlertInfo = function (text) {
    window.htcccAlert({ title: "Notice", text: text || "", icon: "info" });
  };

  (function () {
    const nativeAlert = window.alert;
    window.alert = function (message) {
      if (typeof Swal === "undefined") {
        nativeAlert(message);
        return;
      }
      Swal.fire({
        icon: "info",
        title: "Notice",
        text: String(message || ""),
        confirmButtonText: "OK"
      });
    };
  })();
</script>

<script>
(function () {
  if (typeof window.postUpdate === "function") {
    window._htcccOriginalPostUpdate = window.postUpdate;

    window.postUpdate = async function (action, extra) {
      if (action !== "accept") {
        return window._htcccOriginalPostUpdate(action, extra);
      }

      const ids = (typeof window.getSelectedIds === "function") ? window.getSelectedIds() : [];
      const count = ids.length || 0;

      if (!count) {
        if (typeof window.htcccAlertWarning === "function") {
          window.htcccAlertWarning("Please select at least one application to schedule.");
        } else {
          alert("Please select at least one application to schedule.");
        }
        return;
      }

      const svcInput = document.querySelector("#service_date");
      const svcDate =
        (extra && extra.service_date) ||
        (svcInput ? (svcInput.value || "").trim() : "");

      if (!svcDate) {
        if (typeof window.htcccAlertWarning === "function") {
          window.htcccAlertWarning("Service date is required.");
        } else {
          alert("Service date is required.");
        }
        return;
      }

      const html = `
        <div style="text-align:left;font-size:14px;">
          <p><strong>Service date:</strong> ${svcDate}</p>
          <p><strong>Selected applications:</strong> ${count}</p>
          <p style="margin-top:8px;">Do you want to set this schedule and send email notifications?</p>
        </div>
      `;

      if (typeof Swal === "undefined") {
        const ok = confirm(
          "Confirm schedule?\n\n" +
            "Service date: " + svcDate + "\n" +
            "Selected applications: " + count + "\n\n" +
            "Proceed with scheduling and sending emails?"
        );
        if (!ok) return;
        return window._htcccOriginalPostUpdate(action, extra);
      }

      const result = await Swal.fire({
        icon: "question",
        title: "Confirm schedule",
        html: html,
        showCancelButton: true,
        confirmButtonText: "Yes, schedule",
        cancelButtonText: "Cancel"
      });

      if (!result.isConfirmed) {
        return;
      }

      return window._htcccOriginalPostUpdate(action, extra);
    };
  }

  const statusSelect = document.getElementById("statusSortSelect");
  if (!statusSelect) return;

  statusSelect.addEventListener("change", function () {
    const val = (this.value || "").toLowerCase();
    const tbody = document.querySelector("#bapTable tbody");
    if (!tbody) return;

    const rows = Array.from(tbody.querySelectorAll("tr"));
    if (!rows.length) return;

    let visible = 0;

    rows.forEach(function (row) {
      const rowStatus = (row.getAttribute("data-status") || "").toLowerCase();
      const match = !val || rowStatus === val;
      row.style.display = match ? "" : "none";
      if (match) visible++;
    });

    if (typeof window.htcccAlertInfo === "function") {
      let label;
      if (!val) {
        label = "Showing all applications (" + visible + ")";
      } else {
        const pretty = val.charAt(0).toUpperCase() + val.slice(1);
        label = "Showing " + pretty + " applications (" + visible + ")";
      }
      window.htcccAlertInfo(label);
    }
  });
})();

(function(){
  const bar = document.querySelector(".action-bar");
  if (bar) {
    const chip = document.createElement("span");
    chip.className = "chip";
    chip.id = "btnBapDownloadListPdf";
    chip.innerHTML = '<i class="fas fa-file-download"></i> Download PDF (List)';
    bar.appendChild(chip);

    chip.addEventListener("click", function(){
      const statusSel = document.getElementById("statusSortSelect");
      const val = (statusSel && statusSel.value) ? statusSel.value.toLowerCase() : "";
      let href = "<?php echo basename(__FILE__); ?>?download=baptism_list_pdf";
      if (val === "pending" || val === "scheduled" || val === "reupload") {
        href += "&status=" + encodeURIComponent(val);
      } else {
        href += "&status=all";
      }
      window.open(href, "_blank");
    });
  }
})();
</script>

</body>
</html>
