<?php
/* wedding-list.php — ONE TABLE (service_wedding), sidebar untouched, internal CSS only */

require_once __DIR__ . '/db-connection.php'; // expects $db_connection (mysqli)

/* Ensure session for admin identity */
if (session_status() !== PHP_SESSION_ACTIVE) {
  @session_start();
}

// Simple esc helper used in HTML output
function h($s){ return htmlspecialchars((string)$s, ENT_QUOTES, 'UTF-8'); }

/* =============================================================================
   Admin display name (DB)
   - Pulls from admin table using session admin_id
   ============================================================================= */
function htccc_admin_display_name_from_db(mysqli $db_connection): string {
  if (session_status() !== PHP_SESSION_ACTIVE) {
    @session_start();
  }

  // CHANGE THIS if your admin table name is different
  $adminTable = 'admin_table';

  // Admin id from session (adjust if your system uses different key)
  $adminId = 0;
  if (!empty($_SESSION['admin_id'])) {
    $adminId = (int)$_SESSION['admin_id'];
  } elseif (!empty($_SESSION['user_id'])) {
    $adminId = (int)$_SESSION['user_id'];
  }

  // If cannot resolve ID, fallback to any session name if exists
  if ($adminId <= 0) {
    if (!empty($_SESSION['admin_lastname']) || !empty($_SESSION['admin_firstname'])) {
      $ln = trim((string)($_SESSION['admin_lastname'] ?? ''));
      $fn = trim((string)($_SESSION['admin_firstname'] ?? ''));
      $mn = trim((string)($_SESSION['admin_middlename'] ?? ''));
      $out = trim($ln . ', ' . $fn . ' ' . $mn);
      return trim(preg_replace('/\s+/', ' ', $out)) ?: 'Admin';
    }
    return 'Admin';
  }

  // Title-case helper (optional)
  $titleCase = function ($s) {
    $s = trim((string)$s);
    if ($s === '') return '';
    return preg_replace_callback(
      '/\b(\p{L})(\p{L}*)/u',
      fn($m) => mb_strtoupper($m[1]).mb_strtolower($m[2]),
      $s
    );
  };

  // Query admin table
  $sql = "SELECT admin_lastname, admin_firstname, admin_middlename
          FROM {$adminTable}
          WHERE admin_id = ?
          LIMIT 1";

  if ($stmt = mysqli_prepare($db_connection, $sql)) {
    mysqli_stmt_bind_param($stmt, "i", $adminId);
    mysqli_stmt_execute($stmt);
    $res = mysqli_stmt_get_result($stmt);

    if ($row = mysqli_fetch_assoc($res)) {
      $ln = $titleCase($row['admin_lastname'] ?? '');
      $fn = $titleCase($row['admin_firstname'] ?? '');
      $mn = $titleCase($row['admin_middlename'] ?? '');

      mysqli_stmt_close($stmt);

      // Format: Lastname, Firstname Middlename
      $name = '';
      if ($ln !== '' && $fn !== '') {
        $name = $ln . ', ' . $fn;
      } elseif ($ln !== '') {
        $name = $ln;
      } elseif ($fn !== '') {
        $name = $fn;
      }

      if ($mn !== '') {
        $name .= ($name !== '' ? ' ' : '') . $mn;
      }

      return $name !== '' ? $name : ('Admin #' . $adminId);
    }

    mysqli_stmt_close($stmt);
  }

  return 'Admin #' . $adminId;
}

/* =============================================================================
   DOMPDF DOWNLOAD – Completed Wedding Services (Styled Standard Version)
   Route: ?download=wedding_pdf
   ========================================================================== */
if (isset($_GET['download']) && $_GET['download'] === 'wedding_pdf') {

    if (!isset($db_connection) || !($db_connection instanceof mysqli)) {
        http_response_code(500);
        echo "Database connection not available.";
        exit;
    }

    // Charset/collation
    @mysqli_set_charset($db_connection, 'utf8mb4');
    @mysqli_query($db_connection, "SET collation_connection = 'utf8mb4_unicode_ci'");

    // Fetch DONE wedding services
    $rowsPdf = [];
    $sqlPdf = "
      SELECT
        service_date,
        appointment_date,
        groom_lastname, groom_firstname, groom_middlename, groom_extension,
        bride_lastname, bride_firstname, bride_middlename, bride_extension
      FROM service_wedding
      WHERE service_status = 'Done'
      ORDER BY service_date DESC, groom_lastname ASC, bride_lastname ASC
    ";
    if ($resPdf = mysqli_query($db_connection, $sqlPdf)) {
        while ($r = mysqli_fetch_assoc($resPdf)) $rowsPdf[] = $r;
        mysqli_free_result($resPdf);
    }

    // Absolute logo path
    $scheme = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
    $base   = $scheme . '://' . $_SERVER['HTTP_HOST'];
    $logo   = $base . '/HTCCC-SYSTEM/image/httc_main-logo.jpg';

    $pdfTitle  = "Wedding Service – Completed Services";
    $generated = date('M d, Y');

    // NEW: Generated by admin
    $generatedBy = htccc_admin_display_name_from_db($db_connection);

    ob_start();
    ?>
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title><?php echo htmlspecialchars($pdfTitle); ?></title>
      <style>
        @page { margin: 18mm 14mm; }
        body {
          font-family: DejaVu Sans, Arial, Helvetica, sans-serif;
          color:#111827;
          font-size:12px;
        }
        .header {
          display:flex;
          align-items:center;
          justify-content:space-between;
          border-bottom:1px solid #e5e7eb;
          padding-bottom:8px;
          margin-bottom:12px;
        }
        .brand { display:flex; gap:10px; align-items:center; }
        .brand img { width:48px; height:48px; border-radius:50%; }
        h1 { margin:0; font-size:18px; }
        .sub { color:#64748b; font-size:12px; }

        table { width:100%; border-collapse:collapse; margin-top:10px; }
        thead th {
          background:#1f2a6b;
          color:#fff;
          padding:8px;
          text-align:left;
          font-weight:700;
        }
        tbody td {
          border-bottom:1px solid #e5e7eb;
          padding:8px;
        }
        .muted { color:#64748b; }
      </style>
    </head>

    <body>
      <div class="header">
        <div class="brand">
          <img src="<?php echo htmlspecialchars($logo); ?>" alt="Logo">
          <div>
            <h1><?php echo htmlspecialchars($pdfTitle); ?></h1>
            <div class="sub">
              Generated: <?php echo htmlspecialchars($generated); ?><br>
              Generated by: <?php echo htmlspecialchars($generatedBy); ?>
            </div>
          </div>
        </div>
        <div class="sub">HTCCC System</div>
      </div>

      <table>
        <thead>
          <tr>
            <th style="width:18%;">Service Date</th>
            <th style="width:18%;">Appointment</th>
            <th style="width:32%;">Groom</th>
            <th style="width:32%;">Bride</th>
          </tr>
        </thead>
        <tbody>
          <?php if (!$rowsPdf): ?>
          <tr>
            <td colspan="4" class="muted" style="text-align:center;">No completed wedding services found.</td>
          </tr>
          <?php else: foreach ($rowsPdf as $r): ?>
            <?php
              // Format service date
              $serviceDate = '—';
              if (!empty($r['service_date'])) {
                  $ts = strtotime($r['service_date']);
                  if ($ts) $serviceDate = date('M d, Y', $ts);
              }

              // Appointment schedule
              $apptStr = '—';
              if (!empty($r['appointment_date'])) {
                  $ta = strtotime($r['appointment_date']);
                  if ($ta) $apptStr = date('M d, Y h:i A', $ta);
              }

              // Groom
              $gParts = [];
              if (!empty($r['groom_lastname']))   $gParts[] = $r['groom_lastname'] . ',';
              if (!empty($r['groom_firstname']))  $gParts[] = $r['groom_firstname'];
              if (!empty($r['groom_middlename'])) $gParts[] = $r['groom_middlename'];
              if (!empty($r['groom_extension']))  $gParts[] = $r['groom_extension'];
              $groomName = trim(implode(' ', $gParts), " ,");

              // Bride
              $bParts = [];
              if (!empty($r['bride_lastname']))   $bParts[] = $r['bride_lastname'] . ',';
              if (!empty($r['bride_firstname']))  $bParts[] = $r['bride_firstname'];
              if (!empty($r['bride_middlename'])) $bParts[] = $r['bride_middlename'];
              if (!empty($r['bride_extension']))  $bParts[] = $r['bride_extension'];
              $brideName = trim(implode(' ', $bParts), " ,");
            ?>
            <tr>
              <td><?php echo htmlspecialchars($serviceDate); ?></td>
              <td><?php echo htmlspecialchars($apptStr); ?></td>
              <td><?php echo htmlspecialchars($groomName ?: '—'); ?></td>
              <td><?php echo htmlspecialchars($brideName ?: '—'); ?></td>
            </tr>
          <?php endforeach; endif; ?>
        </tbody>
      </table>
    </body>
    </html>
    <?php
    $html = ob_get_clean();

    require __DIR__ . '/vendor/autoload.php';

    $options = new \Dompdf\Options();
    $options->set('isRemoteEnabled', true);
    $options->set('defaultFont', 'DejaVu Sans');

    $dompdf = new \Dompdf\Dompdf($options);
    $dompdf->loadHtml($html);
    $dompdf->setPaper('A4', 'portrait');
    $dompdf->render();

    $fname = 'Wedding_Completed_' . date('Y-m-d_His') . '.pdf';
    $dompdf->stream($fname, ['Attachment' => true]);
    exit;
}

/* =============================================================================
   HTML PAGE DATA LOAD (service_wedding joined with individual_table)
   (keeps your original "Done" filter pattern)
   ========================================================================== */

$rows = [];
if (isset($db_connection) && $db_connection instanceof mysqli) {
    $sql = "
      SELECT
        w.wedding_id,
        w.individual_id,
        w.service_date,
        w.appointment_date,
        w.groom_lastname, w.groom_firstname, w.groom_middlename, w.groom_extension, w.groom_birthdate,
        w.groom_valid_id_path, w.groom_cenomar_path, w.groom_birth_cert_path, w.groom_widowed_file,
        w.bride_lastname, w.bride_firstname, w.bride_middlename, w.bride_extension, w.bride_birthdate,
        w.bride_valid_id_path, w.bride_cenomar_path, w.bride_baptismal_cert_path, w.bride_widowed_file,
        i.individual_lastname, i.individual_firstname, i.individual_middlename, i.individual_extension,
        i.img_baptismal_cert
      FROM service_wedding w
      LEFT JOIN individual_table i
        ON (i.individual_id = w.individual_id OR i.individual_id = w.individual_id)
      ORDER BY w.service_date DESC, w.groom_lastname ASC, w.bride_lastname ASC
    ";
    if ($res = $db_connection->query($sql)) {
        while ($r = $res->fetch_assoc()) {
            // Raw + formatted dates
            if (!empty($r['service_date'])) {
                $ts = strtotime($r['service_date']);
                $r['_service_date_raw']  = date('Y-m-d', $ts);
                $r['_service_date_disp'] = date('M d, Y', $ts);
            } else {
                $r['_service_date_raw']  = '';
                $r['_service_date_disp'] = '';
            }

            if (!empty($r['appointment_date'])) {
                $ts = strtotime($r['appointment_date']);
                $r['_appointment_raw']   = date('Y-m-d H:i:s', $ts);
                $r['_appointment_date']  = date('M d, Y', $ts);
                $r['_appointment_time']  = date('h:i A', $ts);
            } else {
                $r['_appointment_raw']  = '';
                $r['_appointment_date'] = '';
                $r['_appointment_time'] = '';
            }

            if (!empty($r['groom_birthdate'])) {
                $ts = strtotime($r['groom_birthdate']);
                $r['_groom_birth_raw']  = date('Y-m-d', $ts);
                $r['_groom_birth_disp'] = date('M d, Y', $ts);
            } else {
                $r['_groom_birth_raw']  = '';
                $r['_groom_birth_disp'] = '';
            }

            if (!empty($r['bride_birthdate'])) {
                $ts = strtotime($r['bride_birthdate']);
                $r['_bride_birth_raw']  = date('Y-m-d', $ts);
                $r['_bride_birth_disp'] = date('M d, Y', $ts);
            } else {
                $r['_bride_birth_raw']  = '';
                $r['_bride_birth_disp'] = '';
            }

            $rows[] = $r;
        }
        $res->free();
    }

    // Filter server-side to show ONLY service_status='Done' (your original pattern)
    $doneIds = [];
    if ($rs = $db_connection->query("SELECT wedding_id FROM service_wedding WHERE service_status='Done'")) {
        while ($x = $rs->fetch_assoc()) {
            if (isset($x['wedding_id'])) {
                $doneIds[(string)$x['wedding_id']] = true;
            }
        }
        $rs->free();
    }
    if (!empty($rows)) {
        $rows = array_values(array_filter($rows, function($r) use ($doneIds) {
            return isset($r['wedding_id']) && isset($doneIds[(string)$r['wedding_id']]);
        }));
    }
}
?>
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta content="width=device-width, initial-scale=1" name="viewport"/>
  <title>HTCCC – Wedding Records</title>
  <link rel="icon" type="image/x-icon" href="image/httc_main-logo.jpg">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
  <link rel="stylesheet" href="/HTCCC-SYSTEM/css/baptismal_application.css?v=<?php echo filemtime($_SERVER['DOCUMENT_ROOT'].'/HTCCC-SYSTEM/css/baptismal_application.css'); ?>">

  <!-- INTERNAL CSS ONLY (Sidebar preserved; page/table/modal redesigned) -->
  <style>
    :root{
      --ink:#0A0E3F; --brand1:#6366F1; --brand2:#22C1C3; --muted:#6b7280;
      --bg:#EEF2FF; --card:#FFFFFF; --stroke:#E0E7FF; --shadow:0 16px 40px rgba(15,23,42,.14);
      --radius:18px; --nav:#00216e;
    }
    *{box-sizing:border-box}
    html,body{margin:0;background:var(--bg);font-family:"Inter",system-ui,-apple-system,Segoe UI,Roboto,Arial,sans-serif;color:#0f172a}
    a{color:inherit;text-decoration:none}

    /* ===== SIDEBAR (STRUCTURE + STYLE UNCHANGED) ===== */
    .sidebar{position:fixed;top:0;left:0;bottom:0;width:280px;background:var(--nav);color:#fff;display:flex;flex-direction:column;padding:18px 16px;overflow-y:auto;z-index:10}
    .brand{display:flex;align-items:center;gap:10px;font-weight:800}
    .brand img{width:26px;height:26px;border-radius:6px}
    .user-card{display:flex;align-items:center;gap:12px;padding:12px 8px;background:rgba(255,255,255,.05);border-radius:12px;margin:14px 0}
    .user-card img{width:40px;height:40px;border-radius:999px;object-fit:cover}
    .user-title{font-weight:700}
    .user-sub{font-size:12px;color:#cbd5e1}
    .nav{display:flex;flex-direction:column;gap:6px}
    .section-title{margin-top:12px;margin-bottom:6px;font-size:11px;letter-spacing:.08em;color:#93a4b8;text-transform:uppercase}
    .navlink{display:flex;align-items:center;gap:10px;color:#e2e8f0;padding:10px 12px;border-radius:10px}
    .navlink i{width:18px;text-align:center}
    .navlink:hover{background:rgba(255,255,255,.06)}
    .navlink.active{background:#1f2937;color:#fff}
    .navlink.logout{color:#fca5a5}

    /* ===== PAGE LAYOUT (main content only) ===== */
    .page{
      margin-left:280px;
      min-height:100dvh;
      padding:26px 30px 32px;
      background:radial-gradient(circle at top left,#D9E4FF 0,#EEF2FF 40%,#E5ECFF 100%);
    }
    .page-inner{
      max-width:1240px;
      margin:0 auto;
    }

    .topbar{
      display:flex;
      align-items:center;
      justify-content:space-between;
      padding:18px 22px;
      border-radius:24px;
      background:linear-gradient(135deg,#0b1220,#111827);
      box-shadow:0 18px 40px rgba(15,23,42,.5);
      color:#E5E7EB;
      margin-bottom:20px;
    }
    .topbar-left h1{
      margin:0;
      font-size:22px;
      font-weight:700;
      letter-spacing:.01em;
      color:#F9FAFB;
    }
    .topbar-left p{
      margin:4px 0 0;
      font-size:13px;
      color:#9CA3AF;
    }
    .topbar-pill{
      font-size:12px;
      padding:6px 12px;
      border-radius:999px;
      background:rgba(96,165,250,.14);
      border:1px solid rgba(129,140,248,.35);
      color:#E5E7EB;
      display:inline-flex;
      align-items:center;
      gap:6px;
    }
    .topbar-pill i{font-size:11px}

    .container{
      background:var(--card);
      border-radius:24px;
      padding:20px 20px 18px;
      box-shadow:var(--shadow);
      border:1px solid rgba(148,163,184,.35);
    }

    /* ===== CONTROLS ===== */
    .top-bar{
      display:flex;
      align-items:center;
      justify-content:space-between;
      gap:12px;
      flex-wrap:wrap;
      margin-bottom:14px;
    }
    .search-box{
      flex:1 1 320px;
      min-width:260px;
      padding:11px 14px 11px 40px;
      border-radius:999px;
      border:1px solid #E0E7FF;
      background:#F9FAFB;
      font-size:14px;
      outline:none;
      transition:.16s ease box-shadow,.16s ease border-color,.16s ease background;
      background-image:url('data:image/svg+xml;utf8,<svg xmlns=%22http://www.w3.org/2000/svg%22 width=%2220%22 height=%2220%22 viewBox=%220 0 24 24%22 fill=%22none%22 stroke=%2294a3b8%22 stroke-width=%222%22 stroke-linecap=%22round%22 stroke-linejoin=%22round%22><circle cx=%2211%22 cy=%2211%22 r=%228%22/><line x1=%2221%22 y1=%2221%22 x2=%2216.65%22 y2=%2216.65%22/></svg>');
      background-repeat:no-repeat;
      background-position:13px center;
    }
    .search-box::placeholder{color:#9CA3AF}
    .search-box:focus{
      background:#FFFFFF;
      border-color:#818CF8;
      box-shadow:0 0 0 1px rgba(129,140,248,.45);
    }

    .actions{
      display:flex;
      align-items:center;
      gap:10px;
      flex-wrap:wrap;
    }
    .select,.btn{
      display:inline-flex;
      align-items:center;
      gap:8px;
      padding:9px 12px;
      border-radius:999px;
      border:1px solid #E0E7FF;
      background:#F9FAFB;
      font-size:13px;
      font-weight:500;
      cursor:pointer;
      outline:none;
      transition:.16s ease box-shadow,.16s ease transform,.16s ease background,.16s ease border-color;
    }
    .select{
      min-width:190px;
      color:#111827;
    }
    .select:focus{
      border-color:#818CF8;
      box-shadow:0 0 0 1px rgba(129,140,248,.55);
      background:#FFFFFF;
    }
    .btn{
      background:linear-gradient(135deg,#4F46E5,#0EA5E9);
      color:#F9FAFB;
      border-color:transparent;
      box-shadow:0 12px 25px rgba(79,70,229,.35);
      font-size:13px;
      padding-inline:14px;
    }
    .btn i{font-size:13px}
    .btn:hover{
      transform:translateY(-1px);
      box-shadow:0 14px 30px rgba(79,70,229,.45);
    }
    .btn:active{
      transform:translateY(0);
      box-shadow:0 8px 20px rgba(79,70,229,.35);
    }

    /* ===== TABLE ===== */
    .table-shell{
      border-radius:20px;
      overflow:hidden;
      border:1px solid #E0E7FF;
      background:#FFFFFF;
    }
    .table-wrap{
      max-height:520px;
      overflow:auto;
      scrollbar-width:thin;
      scrollbar-color:#CBD5F5 transparent;
    }
    .table-wrap::-webkit-scrollbar{width:8px}
    .table-wrap::-webkit-scrollbar-track{background:transparent}
    .table-wrap::-webkit-scrollbar-thumb{
      background:#CBD5F5;
      border-radius:999px;
    }

    table{
      width:100%;
      border-collapse:separate;
      border-spacing:0;
      table-layout:fixed;
      font-size:13px;
    }
    thead th{
      position:sticky;
      top:0;
      z-index:1;
      background:linear-gradient(135deg,#111827,#020617);
      color:#E5E7EB;
      padding:11px 12px;
      text-align:left;
      font-weight:600;
      letter-spacing:.03em;
      text-transform:uppercase;
      font-size:11px;
      border-bottom:1px solid rgba(148,163,184,.55);
    }
    tbody tr{
      background:#FFFFFF;
      border-bottom:1px solid #F1F5F9;
      transition:.12s ease background,.12s ease transform,.12s ease box-shadow;
    }
    tbody td{
      padding:11px 12px;
      vertical-align:middle;
      color:#0f172a;
      border-bottom:1px solid #EEF2FF;
      white-space:nowrap;
      overflow:hidden;
      text-overflow:ellipsis;
    }
    tbody tr:hover{
      background:#F9FAFF;
      box-shadow:0 8px 20px rgba(148,163,184,.2);
      transform:translateY(-1px);
    }
    tbody tr:last-child td{border-bottom:none}

    colgroup col:nth-child(1){width:140px}
    colgroup col:nth-child(2){width:190px}
    colgroup col:nth-child(3){width:190px}
    colgroup col:nth-child(4){width:190px}
    colgroup col:nth-child(5){width:90px}
    colgroup col:nth-child(6){width:120px}

    .action-cell{text-align:center}

    .btn-view{
      background:#111827;
      color:#F9FAFB;
      border:0;
      border-radius:999px;
      padding:7px 12px;
      font-size:12px;
      font-weight:500;
      cursor:pointer;
      display:inline-flex;
      align-items:center;
      gap:6px;
      transition:.16s ease background,.16s ease box-shadow,.16s ease transform;
    }
    .btn-view i{font-size:12px}
    .btn-view:hover{
      background:#020617;
      transform:translateY(-0.5px);
      box-shadow:0 10px 20px rgba(15,23,42,.45);
    }
    .btn-view:active{
      transform:translateY(0);
      box-shadow:0 4px 10px rgba(15,23,42,.35);
    }

    /* Empty state row */
    .empty-row td{
      text-align:center;
      padding:32px 16px;
      font-size:14px;
      color:#9CA3AF;
    }

    /* ===== MODAL (redesigned like screenshot) ===== */
    .modal-backdrop{
      position:fixed;
      inset:0;
      background:rgba(15,23,42,.65);
      display:none;
      align-items:center;
      justify-content:center;
      z-index:9999;
      backdrop-filter:blur(4px);
    }
    .modal-backdrop.open{display:flex}

    .modal{
      width:min(1000px,96vw);
      background:#F9FAFB;
      border-radius:24px;
      overflow:hidden;
      box-shadow:0 30px 85px rgba(15,23,42,.75);
      border:1px solid rgba(148,163,184,.5);
      display:flex;
      flex-direction:column;
      max-height:90vh;
    }
    .modal header{
      padding:16px 22px;
      background:#0b1120;
      color:#E5E7EB;
      display:flex;
      align-items:center;
      justify-content:space-between;
    }
    .modal header h3{
      margin:0;
      font-size:18px;
      font-weight:600;
      display:flex;
      align-items:center;
      gap:10px;
    }
    .modal header h3 i{
      padding:6px;
      border-radius:999px;
      background:rgba(30,64,175,.7);
      font-size:13px;
    }
    .modal-subtitle{
      font-size:12px;
      color:#9CA3AF;
      margin-top:2px;
    }
    .close-btn{
      background:transparent;
      color:#E5E7EB;
      border:1px solid rgba(148,163,184,.6);
      border-radius:999px;
      width:30px;
      height:30px;
      display:flex;
      align-items:center;
      justify-content:center;
      font-size:18px;
      cursor:pointer;
      transition:.15s ease background,.15s ease color,.15s ease transform;
    }
    .close-btn:hover{
      background:#020617;
      transform:scale(1.02);
    }

    .modal .body{
      padding:18px 22px 20px;
      overflow:auto;
      scrollbar-width:thin;
      scrollbar-color:#CBD5F5 transparent;
    }
    .modal .body::-webkit-scrollbar{width:8px}
    .modal .body::-webkit-scrollbar-thumb{
      background:#CBD5F5;
      border-radius:999px;
    }

    .modal-section{
      background:#FFFFFF;
      border-radius:18px;
      padding:14px 16px 10px;
      border:1px solid #E0E7FF;
      margin-bottom:14px;
      box-shadow:0 8px 18px rgba(148,163,184,.25);
    }
    .modal-section-title{
      margin:0 0 10px;
      font-size:13px;
      font-weight:700;
      color:#111827;
      display:flex;
      align-items:center;
      gap:8px;
    }
    .modal-section-title::before{
      content:"";
      display:inline-block;
      width:3px;
      height:15px;
      border-radius:999px;
      background:linear-gradient(180deg,#4F46E5,#22C1C3);
    }

    .kv{
      display:grid;
      grid-template-columns:210px 1fr;
      gap:8px 18px;
      font-size:13px;
      padding:7px 0;
      border-top:1px dashed #E5E7EB;
    }
    .kv:first-of-type{border-top:none;padding-top:0}
    .kv-label{
      color:#6B7280;
      font-weight:600;
    }
    .kv-value{
      color:#111827;
      word-break:break-word;
    }
    .kv-value .muted{
      color:#9CA3AF;
      font-style:italic;
    }
    .file-link a{
      color:#2563EB;
      text-decoration:underline;
      font-weight:500;
    }
    .file-path{
      font-size:11px;
      color:#94A3B8;
      margin-top:2px;
      word-break:break-all;
    }

    /* ===== IMAGE VIEWER (copied logic pattern) ===== */
    .imgbox{
      position:fixed;
      inset:0;
      display:none;
      align-items:center;
      justify-content:center;
      background:rgba(0,0,0,.6);
      z-index:100000;
      padding:16px;
    }
    .imgbox[aria-hidden="false"]{ display:flex; }
    .imgbox-inner{
      position:relative;
      max-width:min(1000px, 96vw);
      max-height:90vh;
      background:#0f1720;
      border:1px solid rgba(255,255,255,.18);
      border-radius:14px;
      box-shadow:0 30px 80px rgba(0,0,0,.5);
      overflow:hidden;
    }
    .imgbox-inner img{
      display:block;
      max-width:100%;
      max-height:90vh;
      height:auto;
      width:auto;
    }
    .imgbox-close{
      position:absolute;
      top:8px; right:8px;
      border:0; background:#1f2a38; color:#fff;
      border-radius:10px; padding:6px 10px;
      cursor:pointer;
      z-index:2;
      font-size:18px;
    }

    /* Responsive modal + table */
    @media (max-width:920px){
      .sidebar{width:240px}
      .page{margin-left:240px;padding:20px}
    }
    @media (max-width:720px){
      .sidebar{position:static;width:auto}
      .page{margin:0;padding:16px}
      .page-inner{max-width:none}
      .topbar{
        flex-direction:column;
        align-items:flex-start;
        gap:8px;
      }

      thead{display:none}
      table,tbody,tr,td{display:block;width:100%}
      tbody tr{
        border:1px solid #E0E7FF;
        border-radius:18px;
        margin:10px 0;
        box-shadow:0 8px 18px rgba(148,163,184,.24);
      }
      tbody td{
        display:flex;
        justify-content:space-between;
        gap:10px;
        border-bottom:1px dashed #E5E7EB;
        padding:9px 12px;
      }
      tbody td:last-child{border-bottom:none}
      tbody td::before{
        content:attr(data-label);
        font-weight:600;
        color:#64748B;
        font-size:12px;
      }
      .action-cell{text-align:right}

      .modal{
        width:96vw;
        border-radius:20px;
      }
      .kv{
        grid-template-columns:1fr;
        gap:4px 0;
      }
    }
  </style>
</head>
<body>

<!-- ===== SIDEBAR (DO NOT TOUCH) ===== -->
<aside class="sidebar">
    <div class="brand">
      <img src="image/httc_main-logo.jpg" alt="" />
      <span>HTCCC SYSTEM</span>
    </div>
    <div class="user-card">
      <img src="css/image/profile.png" alt="user">
      <div>
        <div class="user-title">Secretary</div>
        <div class="user-sub">Dashboard</div>
      </div>
    </div>
    <nav class="nav">
      <div class="section-title">Main</div>
      <a class="navlink" href="secretary_dashboard.php"><i class="fas fa-home"></i>Dashboard</a>
      <div class="section-title">Online Requests</div>
      <a class="navlink" href="admin-schedule-request.php"><i class="fas fa-calendar-plus"></i>Schedule Requests</a>
      <a class="navlink" href="admin-prayer-request.php"><i class="fas fa-praying-hands"></i><span>Prayer Requests</span></a>
      <div class="section-title">Online Applications</div>
      <a class="navlink" href="baptismal_application.php"><i class="fas fa-water"></i>Baptismal Applications</a>
      <a class="navlink" href="admin-application.php"><i class="fas fa-user-cog"></i>Baptismal Account Verification</a>
      <a class="navlink" href="application_ministry.php"><i class="fas fa-users"></i>Ministry Applications</a>
      <div class="section-title">Schedule</div>
      <a class="navlink" href="appointment-schedule.php"><i class="fas fa-calendar-check"></i>Service Schedule</a>
      <div class="section-title">All Done Services</div>
      <a class="navlink active" href="done-service-wedding.php"><i class="fas fa-ring"></i>Wedding Service</a>
      <a class="navlink" href="done-service-dedication.php"><i class="fas fa-baby"></i>Child Dedication</a>
      <a class="navlink" href="done-service-funeral.php"><i class="fas fa-cross"></i>Funeral Service</a>
      <a class="navlink" href="done-service-house.php"><i class="fas fa-home"></i>House Blessing</a>
      <a class="navlink" href="done-service-baptism.php"><i class="fas fa-tint"></i>Water Baptism</a>
      <div class="section-title">Streaming</div>
      <a class="navlink" href="admin-multimedia.php"><i class="fas fa-broadcast-tower"></i>Streaming</a>
       <div class="section-title">Individual Management</div>
      <a class="navlink" href="admin-individual_list.php"><i class="fas fa-user"></i>Individual List</a>
      <div class="section-title">Ministry Management</div>
      <a class="navlink" href="admin-ministry-women.php"><i class="fas fa-female"></i>Handmaid of the Lord</a>
      <a class="navlink" href="admin-ministry-men.php"><i class="fas fa-male"></i>Men Ministry</a>
      <a class="navlink" href="admin-ministry-music.php"><i class="fas fa-music"></i>Music Ministry</a>
      <a class="navlink" href="admin-ministry-usher.php"><i class="fas fa-hands-helping"></i>Usher &amp; Usherette</a>
      <div class="section-title">Reports</div>
      <a class="navlink" href="admin-reports.php"><i class="fas fa-file-alt"></i>Reports</a>
      <div class="section-title">Content</div>
      <a class="navlink" href="content-management_home-page.php"><i class="fas fa-edit"></i>Content Management</a>
      <div class="section-title">Certificates</div>
      <a class="navlink" href="certificate-table.php"><i class="fas fa-award"></i>Generate Certificate</a>
      <div class="section-title">Account</div>
      <a class="navlink" href="admin-account-settings.php"><i class="fas fa-user-shield"></i>Account Settings</a>
      <div class="section-title">More</div>
      <a class="navlink logout" href="all_log-in.php"><i class="fas fa-sign-out-alt"></i>Log Out</a>
    </nav>
  </aside>

<div class="page">
  <div class="page-inner">
    <div class="topbar">
      <div class="topbar-left">
        <h1>Wedding Service Records</h1>
        <p>Review all completed wedding services and view full appointment details.</p>
      </div>
      <div class="topbar-pill">
        <i class="fas fa-filter"></i>
        Showing records with status <strong>Done</strong>
      </div>
    </div>

    <div class="container">
      <div class="top-bar">
        <input id="searchInput" class="search-box" type="text" placeholder="Search by name, date or appointment..." autocomplete="off">
        <div class="actions">
          <select id="sortGroom" class="select" aria-label="Sort by Groom">
            <option value="">Sort by Groom (A–Z)</option>
            <option value="groom">Groom Last Name</option>
          </select>
          <select id="sortBride" class="select" aria-label="Sort by Bride">
            <option value="">Sort by Bride (A–Z)</option>
            <option value="bride">Bride Last Name</option>
          </select>
          <select id="sortDate" class="select" aria-label="Sort by Date">
            <option value="">Sort by Service Date</option>
            <option value="date_desc">Newest to Oldest</option>
          </select>
          <button id="applySort" class="btn" type="button">
            <i class="fas fa-sort-amount-down-alt"></i>
            Apply Sort
          </button>
          <!-- PDF Download button -->
          <button class="btn" type="button"
                  onclick="window.location='<?php echo h($_SERVER['PHP_SELF']); ?>?download=wedding_pdf'">
            <i class="fas fa-file-pdf"></i> Download PDF
          </button>
        </div>
      </div>

      <div class="table-shell">
        <div class="table-wrap">
          <table id="dataTable">
            <colgroup>
              <col><col><col><col><col><col>
            </colgroup>
            <thead>
              <tr>
                <th>Service Date</th>
                <th>Last Name</th>
                <th>First Name</th>
                <th>Middle Name</th>
                <th>Extension</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody id="tableBody">
              <?php if (!empty($rows)): ?>
                <?php foreach ($rows as $r): ?>
                  <tr
                    data-service_date="<?php echo h($r['_service_date_raw']); ?>"
                    data-appointment_raw="<?php echo h($r['_appointment_raw']); ?>"
                    data-appointment_date="<?php echo h($r['_appointment_date']); ?>"
                    data-appointment_time="<?php echo h($r['_appointment_time']); ?>"

                    data-individual_lastname="<?php echo h($r['individual_lastname']); ?>"
                    data-individual_firstname="<?php echo h($r['individual_firstname']); ?>"
                    data-individual_middlename="<?php echo h($r['individual_middlename']); ?>"
                    data-individual_extension="<?php echo h($r['individual_extension']); ?>"

                    data-groom_lastname="<?php echo h($r['groom_lastname']); ?>"
                    data-groom_firstname="<?php echo h($r['groom_firstname']); ?>"
                    data-groom_middlename="<?php echo h($r['groom_middlename']); ?>"
                    data-groom_extension="<?php echo h($r['groom_extension']); ?>"
                    data-groom_birth_raw="<?php echo h($r['_groom_birth_raw']); ?>"
                    data-groom_birthdate="<?php echo h($r['_groom_birth_disp']); ?>"
                    data-groom_valid_id_path="<?php echo h($r['groom_valid_id_path']); ?>"
                    data-groom_cenomar_path="<?php echo h($r['groom_cenomar_path']); ?>"
                    data-groom_birth_cert_path="<?php echo h($r['groom_birth_cert_path']); ?>"
                    data-groom_widowed_file="<?php echo h($r['groom_widowed_file']); ?>"

                    data-bride_lastname="<?php echo h($r['bride_lastname']); ?>"
                    data-bride_firstname="<?php echo h($r['bride_firstname']); ?>"
                    data-bride_middlename="<?php echo h($r['bride_middlename']); ?>"
                    data-bride_extension="<?php echo h($r['bride_extension']); ?>"
                    data-bride_birth_raw="<?php echo h($r['_bride_birth_raw']); ?>"
                    data-bride_birthdate="<?php echo h($r['_bride_birth_disp']); ?>"
                    data-bride_valid_id_path="<?php echo h($r['bride_valid_id_path']); ?>"
                    data-bride_cenomar_path="<?php echo h($r['bride_cenomar_path']); ?>"
                    data-bride_baptismal_cert_path="<?php echo h($r['bride_baptismal_cert_path']); ?>"
                    data-bride_widowed_file="<?php echo h($r['bride_widowed_file']); ?>"

                    data-img_baptismal_cert="<?php echo h($r['img_baptismal_cert']); ?>"
                  >
                    <td data-label="Service Date"><?php echo h($r['_service_date_disp']); ?></td>
                    <td data-label="Last Name"><?php echo h($r['individual_lastname']); ?></td>
                    <td data-label="First Name"><?php echo h($r['individual_firstname']); ?></td>
                    <td data-label="Middle Name"><?php echo h($r['individual_middlename']); ?></td>
                    <td data-label="Extension"><?php echo h($r['individual_extension']); ?></td>
                    <td data-label="Action" class="action-cell">
                      <button class="btn-view" type="button"><i class="fas fa-eye"></i> View</button>
                    </td>
                  </tr>
                <?php endforeach; ?>
              <?php else: ?>
                <tr class="empty-row">
                  <td colspan="6">No completed wedding services found.</td>
                </tr>
              <?php endif; ?>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  </div>
</div>

<!-- ===== WEDDING APPOINTMENT DETAILS MODAL ===== -->
<div class="modal-backdrop" id="viewModalBackdrop" role="dialog" aria-modal="true" aria-hidden="true">
  <div class="modal" role="document" aria-label="Wedding appointment details">
    <header>
      <div>
        <h3><i class="fas fa-ring"></i> Wedding Appointment Details</h3>
        <div class="modal-subtitle">View complete information for this wedding service.</div>
      </div>
      <button class="close-btn" id="modalCloseBtn" aria-label="Close">&times;</button>
    </header>
    <div class="body" id="modalBody"><!-- filled by JS --></div>
  </div>
</div>

<!-- ===== IMAGE VIEWER (shared for all image documents) ===== -->
<div id="imgBox" class="imgbox" aria-hidden="true">
  <div class="imgbox-inner">
    <button type="button" class="imgbox-close" id="imgBoxCloseBtn">×</button>
    <img id="imgBoxImg" alt="Document image">
  </div>
</div>

<!-- ===== JS: Search • Sort • Modal ===== -->
<script>
(function(){
  const $  = (s,root=document)=>root.querySelector(s);
  const $$ = (s,root=document)=>Array.from(root.querySelectorAll(s));
  const tableBody   = $('#tableBody');
  const searchInput = $('#searchInput');
  const sortGroom   = $('#sortGroom');
  const sortBride   = $('#sortBride');
  const sortDate    = $('#sortDate');
  const applySort   = $('#applySort');

  // Modal elements
  const backdrop = $('#viewModalBackdrop');
  const modalBody = $('#modalBody');
  const closeBtn = $('#modalCloseBtn');

  // Image viewer elements
  const imgBox = document.getElementById('imgBox');
  const imgBoxImg = document.getElementById('imgBoxImg');
  const imgBoxCloseBtn = document.getElementById('imgBoxCloseBtn');

  const esc = s => (s ?? '').toString().replace(/[&<>"']/g, c=>({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' }[c]));

  // Helper similar to PHP to_url()
  function toUrl(p){
    const v = (p || '').trim();
    if (!v) return '';
    if (/^https?:\/\//i.test(v)) return v;
    return '/' + v.replace(/^\/+/, '');
  }

  // Helper similar to PHP is_image_path()
  function isImagePath(p){
    const v = (p || '').toLowerCase();
    const m = v.match(/\.([a-z0-9]+)(?:[?#]|$)/);
    if (!m) return false;
    const ext = m[1];
    return ['jpg','jpeg','png','gif','webp','bmp'].includes(ext);
  }

  function fileMarkup(path){
    const val = (path || '').trim();
    if (!val) {
      return '<span class="muted">—</span>';
    }
    const url = toUrl(val);
    const safeUrl = esc(url);
    let controlHtml;

    if (isImagePath(url)) {
      // images use an overlay viewer
      controlHtml = `
        <button type="button"
                class="btn-view view-image"
                data-img="${safeUrl}">
          <i class="fas fa-image"></i>
          View image
        </button>
      `;
    } else {
      // PDFs / other docs open in new tab
      controlHtml = `
        <a href="${safeUrl}" target="_blank" rel="noopener">
          Open file
        </a>
      `;
    }

    return `
      <div class="file-link">
        ${controlHtml}
        <div class="file-path">${safeUrl}</div>
      </div>
    `;
  }

  function textOrDash(v){
    const val = (v || '').toString().trim();
    return val ? esc(val) : '<span class="muted">—</span>';
  }

  function openModal(tr){
    // Baptismal cert fallbacks
    const groomBapt = tr.dataset.groom_birth_cert_path || tr.dataset.img_baptismal_cert || '';
    const brideBapt = tr.dataset.bride_baptismal_cert_path || tr.dataset.img_baptismal_cert || '';

    const html = `
      <section class="modal-section">
        <h4 class="modal-section-title">Appointment Information</h4>
        <div class="kv">
          <div class="kv-label">Service Date</div>
          <div class="kv-value">${textOrDash(tr.dataset.service_date ? new Date(tr.dataset.service_date).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'2-digit'}) : '')}</div>
        </div>
        <div class="kv">
          <div class="kv-label">Appointment Date</div>
          <div class="kv-value">${textOrDash(tr.dataset.appointmentDate)}</div>
        </div>
        <div class="kv">
          <div class="kv-label">Appointment Time</div>
          <div class="kv-value">${textOrDash(tr.dataset.appointmentTime)}</div>
        </div>
      </section>

      <section class="modal-section">
        <h4 class="modal-section-title">Groom Information</h4>
        <div class="kv"><div class="kv-label">Last Name</div><div class="kv-value">${textOrDash(tr.dataset.groom_lastname)}</div></div>
        <div class="kv"><div class="kv-label">First Name</div><div class="kv-value">${textOrDash(tr.dataset.groom_firstname)}</div></div>
        <div class="kv"><div class="kv-label">Middle Name</div><div class="kv-value">${textOrDash(tr.dataset.groom_middlename)}</div></div>
        <div class="kv"><div class="kv-label">Extension</div><div class="kv-value">${textOrDash(tr.dataset.groom_extension)}</div></div>
        <div class="kv"><div class="kv-label">Birthdate</div><div class="kv-value">${textOrDash(tr.dataset.groom_birthdate)}</div></div>
        <div class="kv"><div class="kv-label">Valid ID</div><div class="kv-value">${fileMarkup(tr.dataset.groom_valid_id_path)}</div></div>
        ${tr.dataset.groom_cenomar_path ? `<div class="kv"><div class="kv-label">CENOMAR</div><div class="kv-value">${fileMarkup(tr.dataset.groom_cenomar_path)}</div></div>` : ``}
        ${groomBapt ? `<div class="kv"><div class="kv-label">Baptismal Certificate</div><div class="kv-value">${fileMarkup(groomBapt)}</div></div>` : ``}
        ${tr.dataset.groom_widowed_file ? `<div class="kv"><div class="kv-label">Widowed Proof</div><div class="kv-value">${fileMarkup(tr.dataset.groom_widowed_file)}</div></div>` : ``}
      </section>

      <section class="modal-section">
        <h4 class="modal-section-title">Bride Information</h4>
        <div class="kv"><div class="kv-label">Last Name</div><div class="kv-value">${textOrDash(tr.dataset.bride_lastname)}</div></div>
        <div class="kv"><div class="kv-label">First Name</div><div class="kv-value">${textOrDash(tr.dataset.bride_firstname)}</div></div>
        <div class="kv"><div class="kv-label">Middle Name</div><div class="kv-value">${textOrDash(tr.dataset.bride_middlename)}</div></div>
        <div class="kv"><div class="kv-label">Extension</div><div class="kv-value">${textOrDash(tr.dataset.bride_extension)}</div></div>
        <div class="kv"><div class="kv-label">Birthdate</div><div class="kv-value">${textOrDash(tr.dataset.bride_birthdate)}</div></div>
        <div class="kv"><div class="kv-label">Valid ID</div><div class="kv-value">${fileMarkup(tr.dataset.bride_valid_id_path)}</div></div>
        ${tr.dataset.bride_cenomar_path ? `<div class="kv"><div class="kv-label">CENOMAR</div><div class="kv-value">${fileMarkup(tr.dataset.bride_cenomar_path)}</div></div>` : ``}
        ${brideBapt ? `<div class="kv"><div class="kv-label">Baptismal Certificate</div><div class="kv-value">${fileMarkup(brideBapt)}</div></div>` : ``}
        ${tr.dataset.bride_widowed_file ? `<div class="kv"><div class="kv-label">Widowed Proof</div><div class="kv-value">${fileMarkup(tr.dataset.bride_widowed_file)}</div></div>` : ``}
      </section>
    `;

    modalBody.innerHTML = html;

    backdrop.classList.add('open');
    backdrop.setAttribute('aria-hidden','false');
  }

  function closeModal(){
    backdrop.classList.remove('open');
    backdrop.setAttribute('aria-hidden','true');
  }

  backdrop.addEventListener('click', e=>{ if(e.target === backdrop) closeModal(); });
  closeBtn.addEventListener('click', closeModal);
  document.addEventListener('keydown', e=>{ if(e.key === 'Escape') closeModal(); });

  function wireViewButtons(){
    $$('.btn-view', tableBody).forEach(btn=>{
      btn.onclick = () => {
        const tr = btn.closest('tr');
        // attach easier names for JS template
        tr.dataset.appointmentDate = tr.dataset.appointment_date || tr.dataset.appointment_date;
        tr.dataset.appointmentTime = tr.dataset.appointment_time || tr.dataset.appointment_time;
        openModal(tr);
      };
    });
  }
  wireViewButtons();

  function applyFilters(){
    const q = (searchInput.value || '').toLowerCase().trim();
    const rows = $$('#tableBody tr');

    rows.forEach(r=>{
      if (r.classList.contains('empty-row')) return;
      r.style.display = '';
      if(q){
        const hay = [
          r.dataset.service_date,
          r.dataset.appointment_raw,
          r.dataset.individual_lastname, r.dataset.individual_firstname, r.dataset.individual_middlename, r.dataset.individual_extension,
          r.dataset.groom_lastname, r.dataset.groom_firstname, r.dataset.groom_middlename, r.dataset.groom_extension,
          r.dataset.bride_lastname, r.dataset.bride_firstname, r.dataset.bride_middlename, r.dataset.bride_extension
        ].join(' ').toLowerCase();
        if(!hay.includes(q)) r.style.display = 'none';
      }
    });

    // Sort
    const dateVal  = sortDate.value;
    const groomVal = sortGroom.value;
    const brideVal = sortBride.value;

    const visible = rows.filter(r=>!r.classList.contains('empty-row') && r.style.display!=='none');

    visible.sort((a,b)=>{
      if (dateVal === 'date_desc') {
        const da = Date.parse(a.dataset.service_date || '1970-01-01');
        const db = Date.parse(b.dataset.service_date || '1970-01-01');
        if (db !== da) return db - da;
      } else if (groomVal === 'groom') {
        const la = (a.dataset.groom_lastname || '').toLowerCase();
        const lb = (b.dataset.groom_lastname || '').toLowerCase();
        if (la !== lb) return la < lb ? -1 : 1;
      } else if (brideVal === 'bride') {
        const la = (a.dataset.bride_lastname || '').toLowerCase();
        const lb = (b.dataset.bride_lastname || '').toLowerCase();
        if (la !== lb) return la < lb ? -1 : 1;
      }

      // Tie breakers
      const da2 = Date.parse(a.dataset.service_date || '1970-01-01');
      const db2 = Date.parse(b.dataset.service_date || '1970-01-01');
      if (db2 !== da2) return db2 - da2;
      const la2 = (a.dataset.individual_lastname || '').toLowerCase();
      const lb2 = (b.dataset.individual_lastname || '').toLowerCase();
      if (la2 !== lb2) return la2 < lb2 ? -1 : 1;
      return 0;
    });

    visible.forEach(r=>tableBody.appendChild(r));
    rows.filter(r=>r.style.display==='none').forEach(r=>tableBody.appendChild(r));

    wireViewButtons();
  }

  searchInput.addEventListener('input', applyFilters);
  applySort.addEventListener('click', applyFilters);

  // ===== IMAGE VIEWER LOGIC (delegated click) =====
  function openImgBox(src){
    if (!imgBox || !imgBoxImg) return;
    imgBoxImg.src = src;
    imgBox.setAttribute('aria-hidden','false');
  }

  function closeImgBox(){
    if (!imgBox || !imgBoxImg) return;
    imgBoxImg.src = '';
    imgBox.setAttribute('aria-hidden','true');
  }

  document.addEventListener('click', (e) => {
    const btn = e.target.closest('.view-image[data-img]');
    if (!btn) return;
    e.preventDefault();
    const src = btn.getAttribute('data-img');
    if (src) openImgBox(src);
  });

  if (imgBox) {
    imgBox.addEventListener('click', (e) => {
      if (e.target === imgBox) {
        closeImgBox();
      }
    });
  }
  if (imgBoxCloseBtn) {
    imgBoxCloseBtn.addEventListener('click', closeImgBox);
  }

  // Initial state
  applyFilters();
})();
</script>

</body>
</html>
