<?php
/* done-service-baptism.php — ONE TABLE (service_baptism), sidebar untouched, internal CSS only
   + DOMPDF export (Done-only) with "Generated by: <Admin Name>"
*/

require_once __DIR__ . '/db-connection.php'; // expects $db_connection (mysqli)

/* ===================== SESSION ===================== */
if (session_status() !== PHP_SESSION_ACTIVE) {
  session_start();
}

if (!function_exists('h')) {
  function h($s){ return htmlspecialchars((string)$s, ENT_QUOTES | ENT_SUBSTITUTE, 'UTF-8'); }
}

/* =============================================================================
   ADMIN DISPLAY NAME (used in PDF header)
   NOTE: Update the table/columns below to match your admin table.
   - If your session key is different, update $adminId line too.
   ========================================================================== */
function getAdminDisplayName(mysqli $db): string {
  $adminId = $_SESSION['admin_id'] ?? $_SESSION['user_id'] ?? null;
  if (!$adminId) return 'Admin';

  // ✅ CHANGE THIS to your real admin table + columns
  $sql = "SELECT admin_lastname, admin_firstname, admin_middlename
          FROM admin_table
          WHERE admin_id = ?
          LIMIT 1";

  if ($stmt = $db->prepare($sql)) {
    $stmt->bind_param("i", $adminId);
    $stmt->execute();
    $res = $stmt->get_result();
    if ($row = $res->fetch_assoc()) {
      $ln = trim($row['admin_lastname'] ?? '');
      $fn = trim($row['admin_firstname'] ?? '');
      $mn = trim($row['admin_middlename'] ?? '');
      $name = trim(($ln ? $ln . ',' : '') . ' ' . $fn . ' ' . $mn);
      return $name ?: 'Admin';
    }
  }
  return 'Admin';
}

/* =============================================================================
   LOAD DONE ROWS (used by page + PDF; same pattern as your Funeral/House pages)
   ========================================================================== */
$rows = [];
if (isset($db_connection) && $db_connection instanceof mysqli) {

  // Try "Done" first; if `service_status` does not exist, fallback to all
  $sqlDone = "
    SELECT
      baptism_id,
      service_date,
      baptized_lastname,
      baptized_firstname,
      baptized_middlename,
      baptized_ext,
      baptized_birthdate,
      email_address,
      guardian_lastname,
      guardian_firstname,
      guardian_middlename,
      guardian_ext,
      guardian_contactnum
    FROM service_baptism
    WHERE service_status = 'Done'
    ORDER BY service_date DESC, baptism_id DESC
  ";

  $res = @$db_connection->query($sqlDone);
  if ($res === false) {
    $sqlFallback = "
      SELECT
        baptism_id,
        service_date,
        baptized_lastname,
        baptized_firstname,
        baptized_middlename,
        baptized_ext,
        baptized_birthdate,
        email_address,
        guardian_lastname,
        guardian_firstname,
        guardian_middlename,
        guardian_ext,
        guardian_contactnum
      FROM service_baptism
      ORDER BY service_date DESC, baptism_id DESC
    ";
    $res = $db_connection->query($sqlFallback);
  }

  if ($res) {
    while ($r = $res->fetch_assoc()) {

      // Service date
      if (!empty($r['service_date'])) {
        $ts = strtotime($r['service_date']);
        $r['_service_date_raw']  = date('Y-m-d', $ts);
        $r['_service_date_disp'] = date('M d, Y', $ts);
      } else {
        $r['_service_date_raw']  = '';
        $r['_service_date_disp'] = '';
      }

      // Birthdate
      if (!empty($r['baptized_birthdate'])) {
        $ts = strtotime($r['baptized_birthdate']);
        $r['_bapt_birth_raw']  = date('Y-m-d', $ts);
        $r['_bapt_birth_disp'] = date('M d, Y', $ts);
      } else {
        $r['_bapt_birth_raw']  = '';
        $r['_bapt_birth_disp'] = '';
      }

      $rows[] = $r;
    }
    $res->free();
  }
}

/* =============================================================================
   === DOMPDF DOWNLOAD: Water Baptism Records (Done only) ===
   Route: done-service-baptism.php?download=baptism_pdf
   ========================================================================== */
if (isset($_GET['download']) && $_GET['download'] === 'baptism_pdf') {

  if (!isset($db_connection) || !($db_connection instanceof mysqli)) {
    http_response_code(500);
    echo "Database connection not available.";
    exit;
  }

  // Charset/collation (avoid collation conflicts)
  @mysqli_set_charset($db_connection, 'utf8mb4');
  @mysqli_query($db_connection, "SET collation_connection = 'utf8mb4_unicode_ci'");

  // If $rows empty for any reason, refetch (Done-only + fallback)
  if (!$rows) {
    $rows = [];
    $sqlDonePdf = "
      SELECT
        baptism_id,
        service_date,
        baptized_lastname,
        baptized_firstname,
        baptized_middlename,
        baptized_ext,
        baptized_birthdate,
        email_address,
        guardian_lastname,
        guardian_firstname,
        guardian_middlename,
        guardian_ext,
        guardian_contactnum
      FROM service_baptism
      WHERE service_status = 'Done'
      ORDER BY service_date DESC, baptism_id DESC
    ";
    $resPdf = @$db_connection->query($sqlDonePdf);
    if ($resPdf === false) {
      $sqlFallbackPdf = "
        SELECT
          baptism_id,
          service_date,
          baptized_lastname,
          baptized_firstname,
          baptized_middlename,
          baptized_ext,
          baptized_birthdate,
          email_address,
          guardian_lastname,
          guardian_firstname,
          guardian_middlename,
          guardian_ext,
          guardian_contactnum
        FROM service_baptism
        ORDER BY service_date DESC, baptism_id DESC
      ";
      $resPdf = $db_connection->query($sqlFallbackPdf);
    }

    if ($resPdf) {
      while ($r = $resPdf->fetch_assoc()) {

        if (!empty($r['service_date'])) {
          $ts = strtotime($r['service_date']);
          $r['_service_date_raw']  = date('Y-m-d', $ts);
          $r['_service_date_disp'] = date('M d, Y', $ts);
        } else {
          $r['_service_date_raw']  = '';
          $r['_service_date_disp'] = '';
        }

        if (!empty($r['baptized_birthdate'])) {
          $ts = strtotime($r['baptized_birthdate']);
          $r['_bapt_birth_raw']  = date('Y-m-d', $ts);
          $r['_bapt_birth_disp'] = date('M d, Y', $ts);
        } else {
          $r['_bapt_birth_raw']  = '';
          $r['_bapt_birth_disp'] = '';
        }

        $rows[] = $r;
      }
      $resPdf->free();
    }
  }

  // Build absolute logo URL (remote-enabled for Dompdf)
  $scheme = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off') ? 'https' : 'http';
  $base   = $scheme . '://' . $_SERVER['HTTP_HOST'];
  $logo   = $base . '/HTCCC-SYSTEM/image/httc_main-logo.jpg';

  $pdfTitle    = "Water Baptism Records — Done Services";
  $generated   = date('M d, Y');
  $generatedBy = getAdminDisplayName($db_connection);

  ob_start();
  ?>
  <!DOCTYPE html>
  <html>
  <head>
    <meta charset="utf-8">
    <title><?php echo htmlspecialchars($pdfTitle, ENT_QUOTES, 'UTF-8'); ?></title>
    <style>
      @page { margin: 18mm 14mm; }
      body {
        font-family: DejaVu Sans, Arial, Helvetica, sans-serif;
        color:#111827;
        font-size:12px;
      }
      .header {
        display:flex;
        align-items:center;
        justify-content:space-between;
        border-bottom:1px solid #e5e7eb;
        padding-bottom:8px;
        margin-bottom:12px;
      }
      .brand {
        display:flex;
        gap:10px;
        align-items:center;
      }
      .brand img {
        width:48px;
        height:48px;
        border-radius:50%;
      }
      h1 {
        margin:0;
        font-size:18px;
      }
      .sub {
        color:#64748b;
        font-size:12px;
        line-height:1.35;
      }
      table {
        width:100%;
        border-collapse:collapse;
      }
      thead th {
        background:#1f2a6b;
        color:#fff;
        padding:8px;
        text-align:left;
        font-weight:700;
        font-size:11px;
      }
      tbody td {
        border-bottom:1px solid #e5e7eb;
        padding:8px;
        font-size:11px;
      }
      .muted { color:#64748b; }
    </style>
  </head>
  <body>
    <div class="header">
      <div class="brand">
        <img src="<?php echo htmlspecialchars($logo, ENT_QUOTES, 'UTF-8'); ?>" alt="Logo">
        <div>
          <h1><?php echo htmlspecialchars($pdfTitle, ENT_QUOTES, 'UTF-8'); ?></h1>
          <div class="sub">
            Generated: <?php echo htmlspecialchars($generated, ENT_QUOTES, 'UTF-8'); ?><br>
            Generated by: <?php echo htmlspecialchars($generatedBy, ENT_QUOTES, 'UTF-8'); ?>
          </div>
        </div>
      </div>
      <div class="sub">HTCCC System</div>
    </div>

    <table>
      <thead>
        <tr>
          <th style="width:14%;">Service Date</th>
          <th style="width:16%;">Last Name</th>
          <th style="width:16%;">First Name</th>
          <th style="width:14%;">Middle Name</th>
          <th style="width:8%;">Ext</th>
          <th style="width:16%;">Birthdate</th>
          <th style="width:16%;">Email</th>
        </tr>
      </thead>
      <tbody>
        <?php if (!$rows): ?>
          <tr>
            <td colspan="7" style="text-align:center;" class="muted">
              No completed water baptism services found.
            </td>
          </tr>
        <?php else: foreach ($rows as $r): ?>
          <tr>
            <td><?php echo h(!empty($r['_service_date_disp']) ? $r['_service_date_disp'] : '—'); ?></td>
            <td><?php echo h($r['baptized_lastname'] ?? ''); ?></td>
            <td><?php echo h($r['baptized_firstname'] ?? ''); ?></td>
            <td><?php echo h($r['baptized_middlename'] ?? ''); ?></td>
            <td><?php echo h($r['baptized_ext'] ?? ''); ?></td>
            <td><?php echo h($r['_bapt_birth_disp'] ?? ''); ?></td>
            <td><?php echo h($r['email_address'] ?? ''); ?></td>
          </tr>
        <?php endforeach; endif; ?>
      </tbody>
    </table>
  </body>
  </html>
  <?php
  $html = ob_get_clean();

  require __DIR__ . '/vendor/autoload.php';

  $options = new \Dompdf\Options();
  $options->set('isRemoteEnabled', true);
  $options->set('defaultFont', 'DejaVu Sans');

  $dompdf = new \Dompdf\Dompdf($options);
  $dompdf->loadHtml($html);
  $dompdf->setPaper('A4', 'portrait');
  $dompdf->render();

  $fname = 'Water_Baptism_Records_Done_' . date('Y-m-d_His') . '.pdf';
  $dompdf->stream($fname, ['Attachment' => true]);
  exit;
}
?>
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8"/>
  <meta content="width=device-width, initial-scale=1" name="viewport"/>
  <title>HTCCC – Water Baptism Records</title>
  <link rel="icon" type="image/x-icon" href="image/httc_main-logo.jpg">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
  <link rel="stylesheet" href="/HTCCC-SYSTEM/css/baptismal_application.css?v=<?php echo filemtime($_SERVER['DOCUMENT_ROOT'].'/HTCCC-SYSTEM/css/baptismal_application.css'); ?>">

  <!-- INTERNAL CSS ONLY (Sidebar preserved; page/table/modal redesigned using wedding-list template) -->
  <style>
    :root{
      --ink:#0A0E3F; --brand1:#6366F1; --brand2:#22C1C3; --muted:#6b7280;
      --bg:#EEF2FF; --card:#FFFFFF; --stroke:#E0E7FF; --shadow:0 16px 40px rgba(15,23,42,.14);
      --radius:18px; --nav:#00216e;
    }
    *{box-sizing:border-box}
    html,body{margin:0;background:var(--bg);font-family:"Inter",system-ui,-apple-system,Segoe UI,Roboto,Arial,sans-serif;color:#0f172a}
    a{color:inherit;text-decoration:none}

    /* ===== SIDEBAR (STRUCTURE + STYLE UNCHANGED) ===== */
    .sidebar{position:fixed;top:0;left:0;bottom:0;width:280px;background:var(--nav);color:#fff;display:flex;flex-direction:column;padding:18px 16px;overflow-y:auto;z-index:10}
    .brand{display:flex;align-items:center;gap:10px;font-weight:800}
    .brand img{width:26px;height:26px;border-radius:6px}
    .user-card{display:flex;align-items:center;gap:12px;padding:12px 8px;background:rgba(255,255,255,.05);border-radius:12px;margin:14px 0}
    .user-card img{width:40px;height:40px;border-radius:999px;object-fit:cover}
    .user-title{font-weight:700}
    .user-sub{font-size:12px;color:#cbd5e1}
    .nav{display:flex;flex-direction:column;gap:6px}
    .section-title{margin-top:12px;margin-bottom:6px;font-size:11px;letter-spacing:.08em;color:#93a4b8;text-transform:uppercase}
    .navlink{display:flex;align-items:center;gap:10px;color:#e2e8f0;padding:10px 12px;border-radius:10px}
    .navlink i{width:18px;text-align:center}
    .navlink:hover{background:rgba(255,255,255,.06)}
    .navlink.active{background:#1f2937;color:#fff}
    .navlink.logout{color:#fca5a5}

    /* ===== PAGE LAYOUT (main content only) ===== */
    .page{
      margin-left:280px;
      min-height:100dvh;
      padding:26px 30px 32px;
      background:radial-gradient(circle at top left,#D9E4FF 0,#EEF2FF 40%,#E5ECFF 100%);
    }
    .page-inner{ max-width:1240px; margin:0 auto; }

    .topbar{
      display:flex; align-items:center; justify-content:space-between;
      padding:18px 22px; border-radius:24px;
      background:linear-gradient(135deg,#0b1220,#111827);
      box-shadow:0 18px 40px rgba(15,23,42,.5);
      color:#E5E7EB; margin-bottom:20px;
    }
    .topbar-left h1{ margin:0; font-size:22px; font-weight:700; letter-spacing:.01em; color:#F9FAFB; }
    .topbar-left p{ margin:4px 0 0; font-size:13px; color:#9CA3AF; }
    .topbar-pill{
      font-size:12px; padding:6px 12px; border-radius:999px;
      background:rgba(96,165,250,.14);
      border:1px solid rgba(129,140,248,.35);
      color:#E5E7EB; display:inline-flex; align-items:center; gap:6px;
    }
    .topbar-pill i{font-size:11px}

    .container{
      background:var(--card);
      border-radius:24px;
      padding:20px 20px 18px;
      box-shadow:var(--shadow);
      border:1px solid rgba(148,163,184,.35);
    }

    /* ===== CONTROLS ===== */
    .top-bar{
      display:flex; align-items:center; justify-content:space-between;
      gap:12px; flex-wrap:wrap; margin-bottom:14px;
    }
    .search-box{
      flex:1 1 320px; min-width:260px;
      padding:11px 14px 11px 40px;
      border-radius:999px;
      border:1px solid #E0E7FF;
      background:#F9FAFB;
      font-size:14px; outline:none;
      transition:.16s ease box-shadow,.16s ease border-color,.16s ease background;
      background-image:url('data:image/svg+xml;utf8,<svg xmlns=%22http://www.w3.org/2000/svg%22 width=%2220%22 height=%2220%22 viewBox=%220 0 24 24%22 fill=%22none%22 stroke=%2294a3b8%22 stroke-width=%222%22 stroke-linecap=%22round%22 stroke-linejoin=%22round%22><circle cx=%2211%22 cy=%2211%22 r=%228%22/><line x1=%2221%22 y1=%2221%22 x2=%2216.65%22 y2=%2216.65%22/></svg>');
      background-repeat:no-repeat;
      background-position:13px center;
    }
    .search-box::placeholder{color:#9CA3AF}
    .search-box:focus{
      background:#FFFFFF;
      border-color:#818CF8;
      box-shadow:0 0 0 1px rgba(129,140,248,.45);
    }

    .actions{
      display:flex; align-items:center; gap:10px; flex-wrap:wrap;
    }
    .select,.btn{
      display:inline-flex; align-items:center; gap:8px;
      padding:9px 12px;
      border-radius:999px;
      border:1px solid #E0E7FF;
      background:#F9FAFB;
      font-size:13px; font-weight:500;
      cursor:pointer; outline:none;
      transition:.16s ease box-shadow,.16s ease transform,.16s ease background,.16s ease border-color;
    }
    .select{ min-width:190px; color:#111827; }
    .select:focus{
      border-color:#818CF8;
      box-shadow:0 0 0 1px rgba(129,140,248,.55);
      background:#FFFFFF;
    }
    .btn{
      background:linear-gradient(135deg,#4F46E5,#0EA5E9);
      color:#F9FAFB;
      border-color:transparent;
      box-shadow:0 12px 25px rgba(79,70,229,.35);
      font-size:13px; padding-inline:14px;
    }
    .btn i{font-size:13px}
    .btn:hover{ transform:translateY(-1px); box-shadow:0 14px 30px rgba(79,70,229,.45); }
    .btn:active{ transform:translateY(0); box-shadow:0 8px 20px rgba(79,70,229,.35); }

    /* ===== TABLE ===== */
    .table-shell{
      border-radius:20px; overflow:hidden;
      border:1px solid #E0E7FF; background:#FFFFFF;
    }
    .table-wrap{
      max-height:520px; overflow:auto;
      scrollbar-width:thin; scrollbar-color:#CBD5F5 transparent;
    }
    .table-wrap::-webkit-scrollbar{width:8px}
    .table-wrap::-webkit-scrollbar-track{background:transparent}
    .table-wrap::-webkit-scrollbar-thumb{ background:#CBD5F5; border-radius:999px; }

    table{
      width:100%;
      border-collapse:separate;
      border-spacing:0;
      table-layout:fixed;
      font-size:13px;
    }
    thead th{
      position:sticky; top:0; z-index:1;
      background:linear-gradient(135deg,#111827,#020617);
      color:#E5E7EB;
      padding:11px 12px;
      text-align:left;
      font-weight:600;
      letter-spacing:.03em;
      text-transform:uppercase;
      font-size:11px;
      border-bottom:1px solid rgba(148,163,184,.55);
    }
    tbody tr{
      background:#FFFFFF;
      border-bottom:1px solid #F1F5F9;
      transition:.12s ease background,.12s ease transform,.12s ease box-shadow;
    }
    tbody td{
      padding:11px 12px;
      vertical-align:middle;
      color:#0f172a;
      border-bottom:1px solid #EEF2FF;
      white-space:nowrap;
      overflow:hidden;
      text-overflow:ellipsis;
    }
    tbody tr:hover{
      background:#F9FAFF;
      box-shadow:0 8px 20px rgba(148,163,184,.2);
      transform:translateY(-1px);
    }
    tbody tr:last-child td{border-bottom:none}

    colgroup col:nth-child(1){width:140px}
    colgroup col:nth-child(2){width:190px}
    colgroup col:nth-child(3){width:190px}
    colgroup col:nth-child(4){width:190px}
    colgroup col:nth-child(5){width:90px}
    colgroup col:nth-child(6){width:120px}

    .action-cell{text-align:center}

    .btn-view{
      background:#111827; color:#F9FAFB;
      border:0; border-radius:999px;
      padding:7px 12px;
      font-size:12px; font-weight:500;
      cursor:pointer;
      display:inline-flex; align-items:center; gap:6px;
      transition:.16s ease background,.16s ease box-shadow,.16s ease transform;
    }
    .btn-view i{font-size:12px}
    .btn-view:hover{
      background:#020617;
      transform:translateY(-0.5px);
      box-shadow:0 10px 20px rgba(15,23,42,.45);
    }
    .btn-view:active{
      transform:translateY(0);
      box-shadow:0 4px 10px rgba(15,23,42,.35);
    }

    .empty-row td{
      text-align:center; padding:32px 16px;
      font-size:14px; color:#9CA3AF;
    }

    /* ===== MODAL ===== */
    .modal-backdrop{
      position:fixed; inset:0;
      background:rgba(15,23,42,.65);
      display:none; align-items:center; justify-content:center;
      z-index:9999; backdrop-filter:blur(4px);
    }
    .modal-backdrop.open{display:flex}
    .modal{
      width:min(1000px,96vw);
      background:#F9FAFB;
      border-radius:24px; overflow:hidden;
      box-shadow:0 30px 85px rgba(15,23,42,.75);
      border:1px solid rgba(148,163,184,.5);
      display:flex; flex-direction:column;
      max-height:90vh;
    }
    .modal header{
      padding:16px 22px;
      background:#0b1120;
      color:#E5E7EB;
      display:flex; align-items:center; justify-content:space-between;
    }
    .modal header h3{
      margin:0; font-size:18px; font-weight:600;
      display:flex; align-items:center; gap:10px;
    }
    .modal header h3 i{
      padding:6px; border-radius:999px;
      background:rgba(30,64,175,.7);
      font-size:13px;
    }
    .modal-subtitle{ font-size:12px; color:#9CA3AF; margin-top:2px; }
    .close-btn{
      background:transparent; color:#E5E7EB;
      border:1px solid rgba(148,163,184,.6);
      border-radius:999px;
      width:30px; height:30px;
      display:flex; align-items:center; justify-content:center;
      font-size:18px; cursor:pointer;
      transition:.15s ease background,.15s ease color,.15s ease transform;
    }
    .close-btn:hover{ background:#020617; transform:scale(1.02); }
    .modal .body{
      padding:18px 22px 20px;
      overflow:auto;
      scrollbar-width:thin;
      scrollbar-color:#CBD5F5 transparent;
    }
    .modal .body::-webkit-scrollbar{width:8px}
    .modal .body::-webkit-scrollbar-thumb{ background:#CBD5F5; border-radius:999px; }

    .modal-section{
      background:#FFFFFF;
      border-radius:18px;
      padding:14px 16px 10px;
      border:1px solid #E0E7FF;
      margin-bottom:14px;
      box-shadow:0 8px 18px rgba(148,163,184,.25);
    }
    .modal-section-title{
      margin:0 0 10px;
      font-size:13px;
      font-weight:700;
      color:#111827;
      display:flex; align-items:center; gap:8px;
    }
    .modal-section-title::before{
      content:"";
      display:inline-block;
      width:3px; height:15px;
      border-radius:999px;
      background:linear-gradient(180deg,#4F46E5,#22C1C3);
    }
    .kv{
      display:grid;
      grid-template-columns:210px 1fr;
      gap:8px 18px;
      font-size:13px;
      padding:7px 0;
      border-top:1px dashed #E5E7EB;
    }
    .kv:first-of-type{border-top:none;padding-top:0}
    .kv-label{ color:#6B7280; font-weight:600; }
    .kv-value{ color:#111827; word-break:break-word; }
    .kv-value .muted{ color:#9CA3AF; font-style:italic; }

    /* ===== IMAGE VIEWER ===== */
    .imgbox{
      position:fixed; inset:0;
      display:none; align-items:center; justify-content:center;
      background:rgba(0,0,0,.6);
      z-index:100000; padding:16px;
    }
    .imgbox[aria-hidden="false"]{ display:flex; }
    .imgbox-inner{
      position:relative;
      max-width:min(1000px, 96vw);
      max-height:90vh;
      background:#0f1720;
      border:1px solid rgba(255,255,255,.18);
      border-radius:14px;
      box-shadow:0 30px 80px rgba(0,0,0,.5);
      overflow:hidden;
    }
    .imgbox-inner img{
      display:block;
      max-width:100%;
      max-height:90vh;
      height:auto;
      width:auto;
    }
    .imgbox-close{
      position:absolute; top:8px; right:8px;
      border:0; background:#1f2a38; color:#fff;
      border-radius:10px; padding:6px 10px;
      cursor:pointer; z-index:2;
      font-size:18px;
    }

    @media (max-width:920px){
      .sidebar{width:240px}
      .page{margin-left:240px;padding:20px}
    }
    @media (max-width:720px){
      .sidebar{position:static;width:auto}
      .page{margin:0;padding:16px}
      .page-inner{max-width:none}
      .topbar{flex-direction:column; align-items:flex-start; gap:8px;}
      thead{display:none}
      table,tbody,tr,td{display:block;width:100%}
      tbody tr{
        border:1px solid #E0E7FF;
        border-radius:18px;
        margin:10px 0;
        box-shadow:0 8px 18px rgba(148,163,184,.24);
      }
      tbody td{
        display:flex;
        justify-content:space-between;
        gap:10px;
        border-bottom:1px dashed #E5E7EB;
        padding:9px 12px;
      }
      tbody td:last-child{border-bottom:none}
      tbody td::before{
        content:attr(data-label);
        font-weight:600;
        color:#64748B;
        font-size:12px;
      }
      .action-cell{text-align:right}
      .modal{ width:96vw; border-radius:20px; }
      .kv{ grid-template-columns:1fr; gap:4px 0; }
    }
  </style>
</head>
<body>

<!-- ===== SIDEBAR (DO NOT TOUCH) ===== -->
<aside class="sidebar">
  <div class="brand">
    <img src="image/httc_main-logo.jpg" alt="" />
    <span>HTCCC SYSTEM</span>
  </div>

  <div class="user-card">
    <img src="css/image/profile.png" alt="user">
    <div>
      <div class="user-title">Secretary</div>
      <div class="user-sub">Dashboard</div>
    </div>
  </div>

  <nav class="nav">
    <div class="section-title">Main</div>
    <a class="navlink" href="secretary_dashboard.php"><i class="fas fa-home"></i>Dashboard</a>

    <div class="section-title">Online Requests</div>
    <a class="navlink" href="admin-schedule-request.php">
      <i class="fas fa-calendar-plus"></i>Schedule Requests
    </a>
    <a class="navlink" href="admin-prayer-request.php">
      <i class="fas fa-praying-hands"></i><span>Prayer Requests</span>
    </a>

    <div class="section-title">Online Applications</div>
    <a class="navlink" href="">
      <i class="fas fa-water"></i>Baptismal Applications
    </a>
    <a class="navlink" href="admin-application.php">
      <i class="fas fa-user-cog"></i>Baptismal Account Verification
    </a>
    <a class="navlink" href="application_ministry.php">
      <i class="fas fa-users"></i>Ministry Applications
    </a>

    <div class="section-title">Schedule</div>
    <a class="navlink" href="appointment-schedule.php">
      <i class="fas fa-calendar-check"></i>Service Schedule
    </a>

    <div class="section-title">All Done Services</div>
    <a class="navlink" href="done-service-wedding.php">
      <i class="fas fa-ring"></i>Wedding Service
    </a>
    <a class="navlink" href="done-service-dedication.php">
      <i class="fas fa-baby"></i>Child Dedication
    </a>
    <a class="navlink" href="done-service-funeral.php">
      <i class="fas fa-cross"></i>Funeral Service
    </a>
    <a class="navlink" href="done-service-house.php">
      <i class="fas fa-home"></i>House Blessing
    </a>
    <a class="navlink active" href="done-service-baptism.php">
      <i class="fas fa-tint"></i>Water Baptism
    </a>

    <div class="section-title">Streaming</div>
    <a class="navlink" href="admin-multimedia.php">
      <i class="fas fa-broadcast-tower"></i>Streaming
    </a>

    <div class="section-title">Ministry Management</div>
    <a class="navlink" href="admin-ministry-women.php">
      <i class="fas fa-female"></i>Handmaid's of the Lord
    </a>
    <a class="navlink" href="admin-ministry-men.php">
      <i class="fas fa-male"></i>Men's Ministry
    </a>
    <a class="navlink" href="admin-ministry-music.php">
      <i class="fas fa-music"></i>Music Ministry
    </a>
    <a class="navlink" href="admin-ministry-usher.php">
      <i class="fas fa-hands-helping"></i>Usher &amp; Usherette
    </a>
    <a class="navlink" href="admin-ministry-junior.php">
      <i class="fas fa-child"></i>Junior Christ Ambassador
    </a>

    <div class="section-title">Reports</div>
    <a class="navlink" href="admin-reports.php">
      <i class="fas fa-file-alt"></i>Reports
    </a>

    <div class="section-title">Content</div>
    <a class="navlink" href="content-management_home-page.php">
      <i class="fas fa-edit"></i>Content Management
    </a>

    <div class="section-title">Certificates</div>
    <a class="navlink" href="certificate-table.php">
      <i class="fas fa-award"></i>Generate Certificate
    </a>

    <div class="section-title">Account</div>
    <a class="navlink" href="admin-account-settings.php">
      <i class="fas fa-user-shield"></i>Account Settings
    </a>

    <div class="section-title">More</div>
    <a class="navlink logout" href="all_log-in.php">
      <i class="fas fa-sign-out-alt"></i>Log Out
    </a>
  </nav>
</aside>

<div class="page">
  <div class="page-inner">
    <div class="topbar">
      <div class="topbar-left">
        <h1>Water Baptism Records</h1>
        <p>Review all completed water baptism services and view baptizand and guardian details.</p>
      </div>
      <div class="topbar-pill">
        <i class="fas fa-filter"></i>
        Showing records with status <strong>Done</strong>
      </div>
    </div>

    <div class="container">
      <div class="top-bar">
        <input id="searchInput" class="search-box" type="text" placeholder="Search by baptizand name, date, email, or guardian..." autocomplete="off">
        <div class="actions">
          <select id="sortBaptizand" class="select" aria-label="Sort by Baptizand">
            <option value="">Sort by Baptizand (A–Z)</option>
            <option value="baptizand">Baptizand Last Name</option>
          </select>
          <select id="sortGuardian" class="select" aria-label="Sort by Guardian">
            <option value="">Sort by Guardian (A–Z)</option>
            <option value="guardian">Guardian Last Name</option>
          </select>
          <select id="sortDate" class="select" aria-label="Sort by Date">
            <option value="">Sort by Service Date</option>
            <option value="date_desc">Newest to Oldest</option>
          </select>
          <button id="applySort" class="btn" type="button">
            <i class="fas fa-sort-amount-down-alt"></i>
            Apply Sort
          </button>

          <!-- PDF Download button -->
          <button id="downloadPdf" class="btn" type="button">
            <i class="fas fa-file-download"></i>
            Download PDF
          </button>
        </div>
      </div>

      <div class="table-shell">
        <div class="table-wrap">
          <table id="dataTable">
            <colgroup>
              <col><col><col><col><col><col>
            </colgroup>
            <thead>
              <tr>
                <th>Service Date</th>
                <th>Last Name</th>
                <th>First Name</th>
                <th>Middle Name</th>
                <th>Extension</th>
                <th>Action</th>
              </tr>
            </thead>
            <tbody id="tableBody">
              <?php if (!empty($rows)): ?>
                <?php foreach ($rows as $r): ?>
                  <tr
                    data-service_date="<?php echo h($r['_service_date_raw']); ?>"
                    data-baptized_lastname="<?php echo h($r['baptized_lastname']); ?>"
                    data-baptized_firstname="<?php echo h($r['baptized_firstname']); ?>"
                    data-baptized_middlename="<?php echo h($r['baptized_middlename']); ?>"
                    data-baptized_ext="<?php echo h($r['baptized_ext']); ?>"
                    data-baptized_birth_raw="<?php echo h($r['_bapt_birth_raw']); ?>"
                    data-baptized_birthdate="<?php echo h($r['_bapt_birth_disp']); ?>"
                    data-email_address="<?php echo h($r['email_address']); ?>"
                    data-guardian_lastname="<?php echo h($r['guardian_lastname']); ?>"
                    data-guardian_firstname="<?php echo h($r['guardian_firstname']); ?>"
                    data-guardian_middlename="<?php echo h($r['guardian_middlename']); ?>"
                    data-guardian_ext="<?php echo h($r['guardian_ext']); ?>"
                    data-guardian_contactnum="<?php echo h($r['guardian_contactnum']); ?>"
                  >
                    <td data-label="Service Date"><?php echo h($r['_service_date_disp']); ?></td>
                    <td data-label="Last Name"><?php echo h($r['baptized_lastname']); ?></td>
                    <td data-label="First Name"><?php echo h($r['baptized_firstname']); ?></td>
                    <td data-label="Middle Name"><?php echo h($r['baptized_middlename']); ?></td>
                    <td data-label="Extension"><?php echo h($r['baptized_ext']); ?></td>
                    <td data-label="Action" class="action-cell">
                      <button class="btn-view" type="button"><i class="fas fa-eye"></i> View</button>
                    </td>
                  </tr>
                <?php endforeach; ?>
              <?php else: ?>
                <tr class="empty-row">
                  <td colspan="6">No completed water baptism services found.</td>
                </tr>
              <?php endif; ?>
            </tbody>
          </table>
        </div>
      </div>

    </div>
  </div>
</div>

<!-- ===== WATER BAPTISM RECORD DETAILS MODAL ===== -->
<div class="modal-backdrop" id="viewModalBackdrop" role="dialog" aria-modal="true" aria-hidden="true">
  <div class="modal" role="document" aria-label="Water baptism record details">
    <header>
      <div>
        <h3><i class="fas fa-tint"></i> Water Baptism Record Details</h3>
        <div class="modal-subtitle">View complete information for this water baptism service.</div>
      </div>
      <button class="close-btn" id="modalCloseBtn" aria-label="Close">&times;</button>
    </header>
    <div class="body" id="modalBody"><!-- filled by JS --></div>
  </div>
</div>

<!-- ===== IMAGE VIEWER (for future image documents) ===== -->
<div id="imgBox" class="imgbox" aria-hidden="true">
  <div class="imgbox-inner">
    <button type="button" class="imgbox-close" id="imgBoxCloseBtn">×</button>
    <img id="imgBoxImg" alt="Document image">
  </div>
</div>

<!-- ===== JS: Search • Sort • Modal + PDF Download ===== -->
<script>
(function(){
  const $  = (s,root=document)=>root.querySelector(s);
  const $$ = (s,root=document)=>Array.from(root.querySelectorAll(s));

  const tableBody     = $('#tableBody');
  const searchInput   = $('#searchInput');
  const sortBaptizand = $('#sortBaptizand');
  const sortGuardian  = $('#sortGuardian');
  const sortDate      = $('#sortDate');
  const applySort     = $('#applySort');
  const downloadPdf   = $('#downloadPdf');

  // Modal elements
  const backdrop  = $('#viewModalBackdrop');
  const modalBody = $('#modalBody');
  const closeBtn  = $('#modalCloseBtn');

  // Image viewer elements
  const imgBox         = document.getElementById('imgBox');
  const imgBoxImg      = document.getElementById('imgBoxImg');
  const imgBoxCloseBtn = document.getElementById('imgBoxCloseBtn');

  const esc = s => (s ?? '').toString().replace(/[&<>"']/g, c=>({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' }[c]));
  function textOrDash(v){
    const val = (v || '').toString().trim();
    return val ? esc(val) : '<span class="muted">—</span>';
  }

  function hasGuardianData(tr){
    const g = [
      tr.dataset.guardian_lastname,
      tr.dataset.guardian_firstname,
      tr.dataset.guardian_middlename,
      tr.dataset.guardian_ext,
      tr.dataset.guardian_contactnum
    ].map(x => (x || '').trim());
    return g.some(v => v.length > 0);
  }

  function openModal(tr){
    const serviceDateDisplay = tr.dataset.service_date
      ? new Date(tr.dataset.service_date).toLocaleDateString(undefined,{year:'numeric',month:'short',day:'2-digit'})
      : '';

    const hasGuardian = hasGuardianData(tr);

    let html = `
      <section class="modal-section">
        <h4 class="modal-section-title">Service Information</h4>
        <div class="kv">
          <div class="kv-label">Service Date</div>
          <div class="kv-value">${textOrDash(serviceDateDisplay)}</div>
        </div>
      </section>

      <section class="modal-section">
        <h4 class="modal-section-title">Baptizand Information</h4>
        <div class="kv">
          <div class="kv-label">Last Name</div>
          <div class="kv-value">${textOrDash(tr.dataset.baptized_lastname)}</div>
        </div>
        <div class="kv">
          <div class="kv-label">First Name</div>
          <div class="kv-value">${textOrDash(tr.dataset.baptized_firstname)}</div>
        </div>
        <div class="kv">
          <div class="kv-label">Middle Name</div>
          <div class="kv-value">${textOrDash(tr.dataset.baptized_middlename)}</div>
        </div>
        <div class="kv">
          <div class="kv-label">Extension</div>
          <div class="kv-value">${textOrDash(tr.dataset.baptized_ext)}</div>
        </div>
        <div class="kv">
          <div class="kv-label">Birthdate</div>
          <div class="kv-value">${textOrDash(tr.dataset.baptized_birthdate)}</div>
        </div>
        <div class="kv">
          <div class="kv-label">Email Address</div>
          <div class="kv-value">${textOrDash(tr.dataset.email_address)}</div>
        </div>
      </section>
    `;

    if (hasGuardian){
      html += `
        <section class="modal-section">
          <h4 class="modal-section-title">Guardian Information</h4>
          <div class="kv">
            <div class="kv-label">Last Name</div>
            <div class="kv-value">${textOrDash(tr.dataset.guardian_lastname)}</div>
          </div>
          <div class="kv">
            <div class="kv-label">First Name</div>
            <div class="kv-value">${textOrDash(tr.dataset.guardian_firstname)}</div>
          </div>
          <div class="kv">
            <div class="kv-label">Middle Name</div>
            <div class="kv-value">${textOrDash(tr.dataset.guardian_middlename)}</div>
          </div>
          <div class="kv">
            <div class="kv-label">Extension</div>
            <div class="kv-value">${textOrDash(tr.dataset.guardian_ext)}</div>
          </div>
          <div class="kv">
            <div class="kv-label">Contact Number</div>
            <div class="kv-value">${textOrDash(tr.dataset.guardian_contactnum)}</div>
          </div>
        </section>
      `;
    }

    modalBody.innerHTML = html;
    backdrop.classList.add('open');
    backdrop.setAttribute('aria-hidden','false');
  }

  function closeModal(){
    backdrop.classList.remove('open');
    backdrop.setAttribute('aria-hidden','true');
  }

  backdrop.addEventListener('click', e=>{ if(e.target === backdrop) closeModal(); });
  closeBtn.addEventListener('click', closeModal);
  document.addEventListener('keydown', e=>{ if(e.key === 'Escape') closeModal(); });

  function wireViewButtons(){
    $$('.btn-view', tableBody).forEach(btn=>{
      btn.onclick = () => {
        const tr = btn.closest('tr');
        if (!tr) return;
        openModal(tr);
      };
    });
  }
  wireViewButtons();

  function applyFilters(){
    const q = (searchInput.value || '').toLowerCase().trim();
    const rows = $$('#tableBody tr');

    rows.forEach(r=>{
      if (r.classList.contains('empty-row')) return;
      r.style.display = '';
      if (q){
        const hay = [
          r.dataset.service_date,
          r.dataset.baptized_lastname,
          r.dataset.baptized_firstname,
          r.dataset.baptized_middlename,
          r.dataset.baptized_ext,
          r.dataset.baptized_birthdate,
          r.dataset.email_address,
          r.dataset.guardian_lastname,
          r.dataset.guardian_firstname,
          r.dataset.guardian_middlename,
          r.dataset.guardian_ext,
          r.dataset.guardian_contactnum
        ].join(' ').toLowerCase();
        if (!hay.includes(q)) r.style.display = 'none';
      }
    });

    const dateVal  = sortDate.value;
    const baptVal  = sortBaptizand.value;
    const guardVal = sortGuardian.value;

    const visible = rows.filter(r=>!r.classList.contains('empty-row') && r.style.display !== 'none');

    visible.sort((a,b)=>{
      if (dateVal === 'date_desc') {
        const da = Date.parse(a.dataset.service_date || '1970-01-01');
        const db = Date.parse(b.dataset.service_date || '1970-01-01');
        if (db !== da) return db - da;
      } else if (baptVal === 'baptizand') {
        const la = (a.dataset.baptized_lastname || '').toLowerCase();
        const lb = (b.dataset.baptized_lastname || '').toLowerCase();
        if (la !== lb) return la < lb ? -1 : 1;
      } else if (guardVal === 'guardian') {
        const la = (a.dataset.guardian_lastname || '').toLowerCase();
        const lb = (b.dataset.guardian_lastname || '').toLowerCase();
        if (la !== lb) return la < lb ? -1 : 1;
      }

      const da2 = Date.parse(a.dataset.service_date || '1970-01-01');
      const db2 = Date.parse(b.dataset.service_date || '1970-01-01');
      if (db2 !== da2) return db2 - da2;

      const la2 = (a.dataset.baptized_lastname || '').toLowerCase();
      const lb2 = (b.dataset.baptized_lastname || '').toLowerCase();
      if (la2 !== lb2) return la2 < lb2 ? -1 : 1;
      return 0;
    });

    visible.forEach(r=>tableBody.appendChild(r));
    rows.filter(r=>r.style.display === 'none').forEach(r=>tableBody.appendChild(r));

    wireViewButtons();
  }

  searchInput.addEventListener('input', applyFilters);
  applySort.addEventListener('click', applyFilters);

  // ===== PDF DOWNLOAD =====
  if (downloadPdf) {
    downloadPdf.addEventListener('click', () => {
      window.location = 'done-service-baptism.php?download=baptism_pdf';
    });
  }

  // ===== IMAGE VIEWER (future-proof) =====
  function openImgBox(src){
    if (!imgBox || !imgBoxImg) return;
    imgBoxImg.src = src;
    imgBox.setAttribute('aria-hidden','false');
  }
  function closeImgBox(){
    if (!imgBox || !imgBoxImg) return;
    imgBoxImg.src = '';
    imgBox.setAttribute('aria-hidden','true');
  }
  document.addEventListener('click', (e) => {
    const btn = e.target.closest('.view-image[data-img]');
    if (!btn) return;
    e.preventDefault();
    const src = btn.getAttribute('data-img');
    if (src) openImgBox(src);
  });
  if (imgBox) {
    imgBox.addEventListener('click', (e) => {
      if (e.target === imgBox) closeImgBox();
    });
  }
  if (imgBoxCloseBtn) {
    imgBoxCloseBtn.addEventListener('click', closeImgBox);
  }

  // Initial
  applyFilters();
})();
</script>

</body>
</html>
